/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsSupRouteImport } from './routes/what-is-sup'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TourismRecreationRouteImport } from './routes/tourism-recreation'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SupOemMoqLeadTimeRouteImport } from './routes/sup-oem-moq-lead-time'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapProductsDotxmlRouteImport } from './routes/sitemap-products[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapNewsDotxmlRouteImport } from './routes/sitemap-news[.]xml'
import { Route as SitemapEsDotxmlRouteImport } from './routes/sitemap-es[.]xml'
import { Route as SearchIndexDotjsonRouteImport } from './routes/search-index[.]json'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RanddcenterRouteImport } from './routes/randdcenter'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ProofCenterRouteImport } from './routes/proof-center'
import { Route as ProductDevelopmentRouteImport } from './routes/product-development'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OemTrustAssuranceRouteImport } from './routes/oem-trust-assurance'
import { Route as OemPaddleRouteImport } from './routes/oem-paddle'
import { Route as OemOdmRouteImport } from './routes/oem-odm'
import { Route as OemMoqGuideRouteImport } from './routes/oem-moq-guide'
import { Route as OemManufacturingRouteImport } from './routes/oem-manufacturing'
import { Route as OdmDevelopmentRouteImport } from './routes/odm-development'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NewBrandTrialOrderRouteImport } from './routes/new-brand-trial-order'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InflatableVsHardboardRouteImport } from './routes/inflatable-vs-hardboard'
import { Route as FishingRouteImport } from './routes/fishing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as EntityDotjsonRouteImport } from './routes/entity[.]json'
import { Route as B2bSolutionsMatrixRouteImport } from './routes/b2b-solutions-matrix'
import { Route as SplatRouteImport } from './routes/$'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125WhoWeServeRouteImport } from './routes/{-$locale}/who-we-serve'
import { Route as Char123LocaleChar125WaitlistRouteImport } from './routes/{-$locale}/waitlist'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125SupStartupBrandsRouteImport } from './routes/{-$locale}/sup-startup-brands'
import { Route as Char123LocaleChar125SupForResortsRouteImport } from './routes/{-$locale}/sup-for-resorts'
import { Route as Char123LocaleChar125SupForClubsRouteImport } from './routes/{-$locale}/sup-for-clubs'
import { Route as Char123LocaleChar125SolutionsRouteImport } from './routes/{-$locale}/solutions'
import { Route as Char123LocaleChar125SearchRouteImport } from './routes/{-$locale}/search'
import { Route as Char123LocaleChar125PrivateLabelSupRouteImport } from './routes/{-$locale}/private-label-sup'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}/privacy'
import { Route as Char123LocaleChar125HowItWorksRouteImport } from './routes/{-$locale}/how-it-works'
import { Route as Char123LocaleChar125GalleryRouteImport } from './routes/{-$locale}/gallery'
import { Route as Char123LocaleChar125CustomizerRouteImport } from './routes/{-$locale}/customizer'
import { Route as Char123LocaleChar125CustomSupManufacturingRouteImport } from './routes/{-$locale}/custom-sup-manufacturing'
import { Route as Char123LocaleChar125CustomSupDevelopmentRouteImport } from './routes/{-$locale}/custom-sup-development'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125ChangelogRouteImport } from './routes/{-$locale}/changelog'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsMdSplatRouteImport } from './routes/docs-md/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AdminWaitlistDotcsvRouteImport } from './routes/admin/waitlist[.]csv'
import { Route as AdminInquiriesDotcsvRouteImport } from './routes/admin/inquiries[.]csv'
import { Route as Char123LocaleChar125AdminRouteRouteImport } from './routes/{-$locale}/admin/route'
import { Route as Char123LocaleChar125SolutionsIndexRouteImport } from './routes/{-$locale}/solutions/index'
import { Route as Char123LocaleChar125ProjectsIndexRouteImport } from './routes/{-$locale}/projects/index'
import { Route as Char123LocaleChar125ProductsIndexRouteImport } from './routes/{-$locale}/products/index'
import { Route as Char123LocaleChar125KnowledgeIndexRouteImport } from './routes/{-$locale}/knowledge/index'
import { Route as Char123LocaleChar125AppIndexRouteImport } from './routes/{-$locale}/app/index'
import { Route as Char123LocaleChar125AdminIndexRouteImport } from './routes/{-$locale}/admin/index'
import { Route as Char123LocaleChar125AboutIndexRouteImport } from './routes/{-$locale}/about/index'
import { Route as Char123LocaleChar125SolutionsSchoolSupRouteImport } from './routes/{-$locale}/solutions/school-sup'
import { Route as Char123LocaleChar125SolutionsResortSupRouteImport } from './routes/{-$locale}/solutions/resort-sup'
import { Route as Char123LocaleChar125SolutionsPrivateLabelSupRouteImport } from './routes/{-$locale}/solutions/private-label-sup'
import { Route as Char123LocaleChar125SolutionsCustomSupRouteImport } from './routes/{-$locale}/solutions/custom-sup'
import { Route as Char123LocaleChar125SolutionsClubSupRouteImport } from './routes/{-$locale}/solutions/club-sup'
import { Route as Char123LocaleChar125ProjectsSlugRouteImport } from './routes/{-$locale}/projects/$slug'
import { Route as Char123LocaleChar125ProductsSeriesRouteImport } from './routes/{-$locale}/products/$series'
import { Route as Char123LocaleChar125KnowledgeSlugRouteImport } from './routes/{-$locale}/knowledge/$slug'
import { Route as Char123LocaleChar125AppFeedbackRouteImport } from './routes/{-$locale}/app/feedback'
import { Route as Char123LocaleChar125AppAccountRouteImport } from './routes/{-$locale}/app/account'
import { Route as Char123LocaleChar125AdminWaitlistRouteImport } from './routes/{-$locale}/admin/waitlist'
import { Route as Char123LocaleChar125AdminUsersRouteImport } from './routes/{-$locale}/admin/users'
import { Route as Char123LocaleChar125AdminInquiriesRouteImport } from './routes/{-$locale}/admin/inquiries'
import { Route as Char123LocaleChar125AdminFeedbackRouteImport } from './routes/{-$locale}/admin/feedback'
import { Route as Char123LocaleChar125AboutSupsfactoryEntityRouteImport } from './routes/{-$locale}/about/supsfactory-entity'
import { Route as Char123LocaleChar125authVerifyEmailRouteImport } from './routes/{-$locale}/(auth)/verify-email'
import { Route as Char123LocaleChar125authResetPasswordRouteImport } from './routes/{-$locale}/(auth)/reset-password'
import { Route as Char123LocaleChar125authRegisterRouteImport } from './routes/{-$locale}/(auth)/register'
import { Route as Char123LocaleChar125authLoginRouteImport } from './routes/{-$locale}/(auth)/login'
import { Route as Char123LocaleChar125authForgotPasswordRouteImport } from './routes/{-$locale}/(auth)/forgot-password'
import { Route as ApiInquiryLogoSplatRouteImport } from './routes/api/inquiry-logo/$'
import { Route as ApiAvatarsSplatRouteImport } from './routes/api/avatars/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const WhatIsSupRoute = WhatIsSupRouteImport.update({
  id: '/what-is-sup',
  path: '/what-is-sup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/what-is-sup.lazy').then((d) => d.Route))
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/warranty.lazy').then((d) => d.Route))
const TourismRecreationRoute = TourismRecreationRouteImport.update({
  id: '/tourism-recreation',
  path: '/tourism-recreation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/tourism-recreation.lazy').then((d) => d.Route),
)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/technology.lazy').then((d) => d.Route))
const SupOemMoqLeadTimeRoute = SupOemMoqLeadTimeRouteImport.update({
  id: '/sup-oem-moq-lead-time',
  path: '/sup-oem-moq-lead-time',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/size-guide.lazy').then((d) => d.Route))
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProductsDotxmlRoute = SitemapProductsDotxmlRouteImport.update({
  id: '/sitemap-products.xml',
  path: '/sitemap-products.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapNewsDotxmlRoute = SitemapNewsDotxmlRouteImport.update({
  id: '/sitemap-news.xml',
  path: '/sitemap-news.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEsDotxmlRoute = SitemapEsDotxmlRouteImport.update({
  id: '/sitemap-es.xml',
  path: '/sitemap-es.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexDotjsonRoute = SearchIndexDotjsonRouteImport.update({
  id: '/search-index.json',
  path: '/search-index.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RanddcenterRoute = RanddcenterRouteImport.update({
  id: '/randdcenter',
  path: '/randdcenter',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/randdcenter.lazy').then((d) => d.Route))
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/quality.lazy').then((d) => d.Route))
const ProofCenterRoute = ProofCenterRouteImport.update({
  id: '/proof-center',
  path: '/proof-center',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/proof-center.lazy').then((d) => d.Route))
const ProductDevelopmentRoute = ProductDevelopmentRouteImport.update({
  id: '/product-development',
  path: '/product-development',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/product-development.lazy').then((d) => d.Route),
)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/partners.lazy').then((d) => d.Route))
const OemTrustAssuranceRoute = OemTrustAssuranceRouteImport.update({
  id: '/oem-trust-assurance',
  path: '/oem-trust-assurance',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/oem-trust-assurance.lazy').then((d) => d.Route),
)
const OemPaddleRoute = OemPaddleRouteImport.update({
  id: '/oem-paddle',
  path: '/oem-paddle',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/oem-paddle.lazy').then((d) => d.Route))
const OemOdmRoute = OemOdmRouteImport.update({
  id: '/oem-odm',
  path: '/oem-odm',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/oem-odm.lazy').then((d) => d.Route))
const OemMoqGuideRoute = OemMoqGuideRouteImport.update({
  id: '/oem-moq-guide',
  path: '/oem-moq-guide',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/oem-moq-guide.lazy').then((d) => d.Route))
const OemManufacturingRoute = OemManufacturingRouteImport.update({
  id: '/oem-manufacturing',
  path: '/oem-manufacturing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/oem-manufacturing.lazy').then((d) => d.Route),
)
const OdmDevelopmentRoute = OdmDevelopmentRouteImport.update({
  id: '/odm-development',
  path: '/odm-development',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/odm-development.lazy').then((d) => d.Route),
)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/news.lazy').then((d) => d.Route))
const NewBrandTrialOrderRoute = NewBrandTrialOrderRouteImport.update({
  id: '/new-brand-trial-order',
  path: '/new-brand-trial-order',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/knowledge.lazy').then((d) => d.Route))
const InflatableVsHardboardRoute = InflatableVsHardboardRouteImport.update({
  id: '/inflatable-vs-hardboard',
  path: '/inflatable-vs-hardboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/inflatable-vs-hardboard.lazy').then((d) => d.Route),
)
const FishingRoute = FishingRouteImport.update({
  id: '/fishing',
  path: '/fishing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/fishing.lazy').then((d) => d.Route))
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/faq.lazy').then((d) => d.Route))
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/factory.lazy').then((d) => d.Route))
const EntityDotjsonRoute = EntityDotjsonRouteImport.update({
  id: '/entity.json',
  path: '/entity.json',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bSolutionsMatrixRoute = B2bSolutionsMatrixRouteImport.update({
  id: '/b2b-solutions-matrix',
  path: '/b2b-solutions-matrix',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/b2b-solutions-matrix.lazy').then((d) => d.Route),
)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/$.lazy').then((d) => d.Route))
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125WhoWeServeRoute =
  Char123LocaleChar125WhoWeServeRouteImport.update({
    id: '/who-we-serve',
    path: '/who-we-serve',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125WaitlistRoute =
  Char123LocaleChar125WaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SupStartupBrandsRoute =
  Char123LocaleChar125SupStartupBrandsRouteImport.update({
    id: '/sup-startup-brands',
    path: '/sup-startup-brands',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SupForResortsRoute =
  Char123LocaleChar125SupForResortsRouteImport.update({
    id: '/sup-for-resorts',
    path: '/sup-for-resorts',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SupForClubsRoute =
  Char123LocaleChar125SupForClubsRouteImport.update({
    id: '/sup-for-clubs',
    path: '/sup-for-clubs',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SolutionsRoute =
  Char123LocaleChar125SolutionsRouteImport.update({
    id: '/solutions',
    path: '/solutions',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SearchRoute =
  Char123LocaleChar125SearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PrivateLabelSupRoute =
  Char123LocaleChar125PrivateLabelSupRouteImport.update({
    id: '/private-label-sup',
    path: '/private-label-sup',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125HowItWorksRoute =
  Char123LocaleChar125HowItWorksRouteImport.update({
    id: '/how-it-works',
    path: '/how-it-works',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125GalleryRoute =
  Char123LocaleChar125GalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CustomizerRoute =
  Char123LocaleChar125CustomizerRouteImport.update({
    id: '/customizer',
    path: '/customizer',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CustomSupManufacturingRoute =
  Char123LocaleChar125CustomSupManufacturingRouteImport.update({
    id: '/custom-sup-manufacturing',
    path: '/custom-sup-manufacturing',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CustomSupDevelopmentRoute =
  Char123LocaleChar125CustomSupDevelopmentRouteImport.update({
    id: '/custom-sup-development',
    path: '/custom-sup-development',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ChangelogRoute =
  Char123LocaleChar125ChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any).lazy(() =>
    import('./routes/{-$locale}/changelog.lazy').then((d) => d.Route),
  )
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/docs/$.lazy').then((d) => d.Route))
const DocsMdSplatRoute = DocsMdSplatRouteImport.update({
  id: '/docs-md/$',
  path: '/docs-md/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistDotcsvRoute = AdminWaitlistDotcsvRouteImport.update({
  id: '/admin/waitlist.csv',
  path: '/admin/waitlist.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesDotcsvRoute = AdminInquiriesDotcsvRouteImport.update({
  id: '/admin/inquiries.csv',
  path: '/admin/inquiries.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AdminRouteRoute =
  Char123LocaleChar125AdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SolutionsIndexRoute =
  Char123LocaleChar125SolutionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125SolutionsRoute,
  } as any)
const Char123LocaleChar125ProjectsIndexRoute =
  Char123LocaleChar125ProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProductsIndexRoute =
  Char123LocaleChar125ProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125KnowledgeIndexRoute =
  Char123LocaleChar125KnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppIndexRoute =
  Char123LocaleChar125AppIndexRouteImport.update({
    id: '/app/',
    path: '/app/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AdminIndexRoute =
  Char123LocaleChar125AdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AboutIndexRoute =
  Char123LocaleChar125AboutIndexRouteImport.update({
    id: '/about/',
    path: '/about/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SolutionsSchoolSupRoute =
  Char123LocaleChar125SolutionsSchoolSupRouteImport.update({
    id: '/school-sup',
    path: '/school-sup',
    getParentRoute: () => Char123LocaleChar125SolutionsRoute,
  } as any)
const Char123LocaleChar125SolutionsResortSupRoute =
  Char123LocaleChar125SolutionsResortSupRouteImport.update({
    id: '/resort-sup',
    path: '/resort-sup',
    getParentRoute: () => Char123LocaleChar125SolutionsRoute,
  } as any)
const Char123LocaleChar125SolutionsPrivateLabelSupRoute =
  Char123LocaleChar125SolutionsPrivateLabelSupRouteImport.update({
    id: '/private-label-sup',
    path: '/private-label-sup',
    getParentRoute: () => Char123LocaleChar125SolutionsRoute,
  } as any)
const Char123LocaleChar125SolutionsCustomSupRoute =
  Char123LocaleChar125SolutionsCustomSupRouteImport.update({
    id: '/custom-sup',
    path: '/custom-sup',
    getParentRoute: () => Char123LocaleChar125SolutionsRoute,
  } as any)
const Char123LocaleChar125SolutionsClubSupRoute =
  Char123LocaleChar125SolutionsClubSupRouteImport.update({
    id: '/club-sup',
    path: '/club-sup',
    getParentRoute: () => Char123LocaleChar125SolutionsRoute,
  } as any)
const Char123LocaleChar125ProjectsSlugRoute =
  Char123LocaleChar125ProjectsSlugRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProductsSeriesRoute =
  Char123LocaleChar125ProductsSeriesRouteImport.update({
    id: '/products/$series',
    path: '/products/$series',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any).lazy(() =>
    import('./routes/{-$locale}/products/$series.lazy').then((d) => d.Route),
  )
const Char123LocaleChar125KnowledgeSlugRoute =
  Char123LocaleChar125KnowledgeSlugRouteImport.update({
    id: '/knowledge/$slug',
    path: '/knowledge/$slug',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppFeedbackRoute =
  Char123LocaleChar125AppFeedbackRouteImport.update({
    id: '/app/feedback',
    path: '/app/feedback',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppAccountRoute =
  Char123LocaleChar125AppAccountRouteImport.update({
    id: '/app/account',
    path: '/app/account',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AdminWaitlistRoute =
  Char123LocaleChar125AdminWaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AdminUsersRoute =
  Char123LocaleChar125AdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AdminInquiriesRoute =
  Char123LocaleChar125AdminInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AdminFeedbackRoute =
  Char123LocaleChar125AdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AboutSupsfactoryEntityRoute =
  Char123LocaleChar125AboutSupsfactoryEntityRouteImport.update({
    id: '/about/supsfactory-entity',
    path: '/about/supsfactory-entity',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authVerifyEmailRoute =
  Char123LocaleChar125authVerifyEmailRouteImport.update({
    id: '/(auth)/verify-email',
    path: '/verify-email',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authResetPasswordRoute =
  Char123LocaleChar125authResetPasswordRouteImport.update({
    id: '/(auth)/reset-password',
    path: '/reset-password',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authRegisterRoute =
  Char123LocaleChar125authRegisterRouteImport.update({
    id: '/(auth)/register',
    path: '/register',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authLoginRoute =
  Char123LocaleChar125authLoginRouteImport.update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authForgotPasswordRoute =
  Char123LocaleChar125authForgotPasswordRouteImport.update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const ApiInquiryLogoSplatRoute = ApiInquiryLogoSplatRouteImport.update({
  id: '/api/inquiry-logo/$',
  path: '/api/inquiry-logo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarsSplatRoute = ApiAvatarsSplatRouteImport.update({
  id: '/api/avatars/$',
  path: '/api/avatars/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/$': typeof SplatRoute
  '/b2b-solutions-matrix': typeof B2bSolutionsMatrixRoute
  '/entity.json': typeof EntityDotjsonRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/fishing': typeof FishingRoute
  '/inflatable-vs-hardboard': typeof InflatableVsHardboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/new-brand-trial-order': typeof NewBrandTrialOrderRoute
  '/news': typeof NewsRoute
  '/odm-development': typeof OdmDevelopmentRoute
  '/oem-manufacturing': typeof OemManufacturingRoute
  '/oem-moq-guide': typeof OemMoqGuideRoute
  '/oem-odm': typeof OemOdmRoute
  '/oem-paddle': typeof OemPaddleRoute
  '/oem-trust-assurance': typeof OemTrustAssuranceRoute
  '/partners': typeof PartnersRoute
  '/product-development': typeof ProductDevelopmentRoute
  '/proof-center': typeof ProofCenterRoute
  '/quality': typeof QualityRoute
  '/randdcenter': typeof RanddcenterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-news.xml': typeof SitemapNewsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/sup-oem-moq-lead-time': typeof SupOemMoqLeadTimeRoute
  '/technology': typeof TechnologyRoute
  '/tourism-recreation': typeof TourismRecreationRoute
  '/warranty': typeof WarrantyRoute
  '/what-is-sup': typeof WhatIsSupRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRouteRouteWithChildren
  '/admin/inquiries.csv': typeof AdminInquiriesDotcsvRoute
  '/admin/waitlist.csv': typeof AdminWaitlistDotcsvRoute
  '/api/search': typeof ApiSearchRoute
  '/docs-md/$': typeof DocsMdSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125ChangelogRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/custom-sup-development': typeof Char123LocaleChar125CustomSupDevelopmentRoute
  '/{-$locale}/custom-sup-manufacturing': typeof Char123LocaleChar125CustomSupManufacturingRoute
  '/{-$locale}/customizer': typeof Char123LocaleChar125CustomizerRoute
  '/{-$locale}/gallery': typeof Char123LocaleChar125GalleryRoute
  '/{-$locale}/how-it-works': typeof Char123LocaleChar125HowItWorksRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/private-label-sup': typeof Char123LocaleChar125PrivateLabelSupRoute
  '/{-$locale}/search': typeof Char123LocaleChar125SearchRoute
  '/{-$locale}/solutions': typeof Char123LocaleChar125SolutionsRouteWithChildren
  '/{-$locale}/sup-for-clubs': typeof Char123LocaleChar125SupForClubsRoute
  '/{-$locale}/sup-for-resorts': typeof Char123LocaleChar125SupForResortsRoute
  '/{-$locale}/sup-startup-brands': typeof Char123LocaleChar125SupStartupBrandsRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/waitlist': typeof Char123LocaleChar125WaitlistRoute
  '/{-$locale}/who-we-serve': typeof Char123LocaleChar125WhoWeServeRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatars/$': typeof ApiAvatarsSplatRoute
  '/api/inquiry-logo/$': typeof ApiInquiryLogoSplatRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125authForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125authLoginRoute
  '/{-$locale}/register': typeof Char123LocaleChar125authRegisterRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125authResetPasswordRoute
  '/{-$locale}/verify-email': typeof Char123LocaleChar125authVerifyEmailRoute
  '/{-$locale}/about/supsfactory-entity': typeof Char123LocaleChar125AboutSupsfactoryEntityRoute
  '/{-$locale}/admin/feedback': typeof Char123LocaleChar125AdminFeedbackRoute
  '/{-$locale}/admin/inquiries': typeof Char123LocaleChar125AdminInquiriesRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/{-$locale}/admin/waitlist': typeof Char123LocaleChar125AdminWaitlistRoute
  '/{-$locale}/app/account': typeof Char123LocaleChar125AppAccountRoute
  '/{-$locale}/app/feedback': typeof Char123LocaleChar125AppFeedbackRoute
  '/{-$locale}/knowledge/$slug': typeof Char123LocaleChar125KnowledgeSlugRoute
  '/{-$locale}/products/$series': typeof Char123LocaleChar125ProductsSeriesRoute
  '/{-$locale}/projects/$slug': typeof Char123LocaleChar125ProjectsSlugRoute
  '/{-$locale}/solutions/club-sup': typeof Char123LocaleChar125SolutionsClubSupRoute
  '/{-$locale}/solutions/custom-sup': typeof Char123LocaleChar125SolutionsCustomSupRoute
  '/{-$locale}/solutions/private-label-sup': typeof Char123LocaleChar125SolutionsPrivateLabelSupRoute
  '/{-$locale}/solutions/resort-sup': typeof Char123LocaleChar125SolutionsResortSupRoute
  '/{-$locale}/solutions/school-sup': typeof Char123LocaleChar125SolutionsSchoolSupRoute
  '/{-$locale}/about/': typeof Char123LocaleChar125AboutIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125AppIndexRoute
  '/{-$locale}/knowledge/': typeof Char123LocaleChar125KnowledgeIndexRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
  '/{-$locale}/projects/': typeof Char123LocaleChar125ProjectsIndexRoute
  '/{-$locale}/solutions/': typeof Char123LocaleChar125SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/b2b-solutions-matrix': typeof B2bSolutionsMatrixRoute
  '/entity.json': typeof EntityDotjsonRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/fishing': typeof FishingRoute
  '/inflatable-vs-hardboard': typeof InflatableVsHardboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/new-brand-trial-order': typeof NewBrandTrialOrderRoute
  '/news': typeof NewsRoute
  '/odm-development': typeof OdmDevelopmentRoute
  '/oem-manufacturing': typeof OemManufacturingRoute
  '/oem-moq-guide': typeof OemMoqGuideRoute
  '/oem-odm': typeof OemOdmRoute
  '/oem-paddle': typeof OemPaddleRoute
  '/oem-trust-assurance': typeof OemTrustAssuranceRoute
  '/partners': typeof PartnersRoute
  '/product-development': typeof ProductDevelopmentRoute
  '/proof-center': typeof ProofCenterRoute
  '/quality': typeof QualityRoute
  '/randdcenter': typeof RanddcenterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-news.xml': typeof SitemapNewsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/sup-oem-moq-lead-time': typeof SupOemMoqLeadTimeRoute
  '/technology': typeof TechnologyRoute
  '/tourism-recreation': typeof TourismRecreationRoute
  '/warranty': typeof WarrantyRoute
  '/what-is-sup': typeof WhatIsSupRoute
  '/admin/inquiries.csv': typeof AdminInquiriesDotcsvRoute
  '/admin/waitlist.csv': typeof AdminWaitlistDotcsvRoute
  '/api/search': typeof ApiSearchRoute
  '/docs-md/$': typeof DocsMdSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125ChangelogRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/custom-sup-development': typeof Char123LocaleChar125CustomSupDevelopmentRoute
  '/{-$locale}/custom-sup-manufacturing': typeof Char123LocaleChar125CustomSupManufacturingRoute
  '/{-$locale}/customizer': typeof Char123LocaleChar125CustomizerRoute
  '/{-$locale}/gallery': typeof Char123LocaleChar125GalleryRoute
  '/{-$locale}/how-it-works': typeof Char123LocaleChar125HowItWorksRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/private-label-sup': typeof Char123LocaleChar125PrivateLabelSupRoute
  '/{-$locale}/search': typeof Char123LocaleChar125SearchRoute
  '/{-$locale}/sup-for-clubs': typeof Char123LocaleChar125SupForClubsRoute
  '/{-$locale}/sup-for-resorts': typeof Char123LocaleChar125SupForResortsRoute
  '/{-$locale}/sup-startup-brands': typeof Char123LocaleChar125SupStartupBrandsRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/waitlist': typeof Char123LocaleChar125WaitlistRoute
  '/{-$locale}/who-we-serve': typeof Char123LocaleChar125WhoWeServeRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatars/$': typeof ApiAvatarsSplatRoute
  '/api/inquiry-logo/$': typeof ApiInquiryLogoSplatRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125authForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125authLoginRoute
  '/{-$locale}/register': typeof Char123LocaleChar125authRegisterRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125authResetPasswordRoute
  '/{-$locale}/verify-email': typeof Char123LocaleChar125authVerifyEmailRoute
  '/{-$locale}/about/supsfactory-entity': typeof Char123LocaleChar125AboutSupsfactoryEntityRoute
  '/{-$locale}/admin/feedback': typeof Char123LocaleChar125AdminFeedbackRoute
  '/{-$locale}/admin/inquiries': typeof Char123LocaleChar125AdminInquiriesRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/{-$locale}/admin/waitlist': typeof Char123LocaleChar125AdminWaitlistRoute
  '/{-$locale}/app/account': typeof Char123LocaleChar125AppAccountRoute
  '/{-$locale}/app/feedback': typeof Char123LocaleChar125AppFeedbackRoute
  '/{-$locale}/knowledge/$slug': typeof Char123LocaleChar125KnowledgeSlugRoute
  '/{-$locale}/products/$series': typeof Char123LocaleChar125ProductsSeriesRoute
  '/{-$locale}/projects/$slug': typeof Char123LocaleChar125ProjectsSlugRoute
  '/{-$locale}/solutions/club-sup': typeof Char123LocaleChar125SolutionsClubSupRoute
  '/{-$locale}/solutions/custom-sup': typeof Char123LocaleChar125SolutionsCustomSupRoute
  '/{-$locale}/solutions/private-label-sup': typeof Char123LocaleChar125SolutionsPrivateLabelSupRoute
  '/{-$locale}/solutions/resort-sup': typeof Char123LocaleChar125SolutionsResortSupRoute
  '/{-$locale}/solutions/school-sup': typeof Char123LocaleChar125SolutionsSchoolSupRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutIndexRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/app': typeof Char123LocaleChar125AppIndexRoute
  '/{-$locale}/knowledge': typeof Char123LocaleChar125KnowledgeIndexRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsIndexRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsIndexRoute
  '/{-$locale}/solutions': typeof Char123LocaleChar125SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/$': typeof SplatRoute
  '/b2b-solutions-matrix': typeof B2bSolutionsMatrixRoute
  '/entity.json': typeof EntityDotjsonRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/fishing': typeof FishingRoute
  '/inflatable-vs-hardboard': typeof InflatableVsHardboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/new-brand-trial-order': typeof NewBrandTrialOrderRoute
  '/news': typeof NewsRoute
  '/odm-development': typeof OdmDevelopmentRoute
  '/oem-manufacturing': typeof OemManufacturingRoute
  '/oem-moq-guide': typeof OemMoqGuideRoute
  '/oem-odm': typeof OemOdmRoute
  '/oem-paddle': typeof OemPaddleRoute
  '/oem-trust-assurance': typeof OemTrustAssuranceRoute
  '/partners': typeof PartnersRoute
  '/product-development': typeof ProductDevelopmentRoute
  '/proof-center': typeof ProofCenterRoute
  '/quality': typeof QualityRoute
  '/randdcenter': typeof RanddcenterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-news.xml': typeof SitemapNewsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/sup-oem-moq-lead-time': typeof SupOemMoqLeadTimeRoute
  '/technology': typeof TechnologyRoute
  '/tourism-recreation': typeof TourismRecreationRoute
  '/warranty': typeof WarrantyRoute
  '/what-is-sup': typeof WhatIsSupRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRouteRouteWithChildren
  '/admin/inquiries.csv': typeof AdminInquiriesDotcsvRoute
  '/admin/waitlist.csv': typeof AdminWaitlistDotcsvRoute
  '/api/search': typeof ApiSearchRoute
  '/docs-md/$': typeof DocsMdSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125ChangelogRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/custom-sup-development': typeof Char123LocaleChar125CustomSupDevelopmentRoute
  '/{-$locale}/custom-sup-manufacturing': typeof Char123LocaleChar125CustomSupManufacturingRoute
  '/{-$locale}/customizer': typeof Char123LocaleChar125CustomizerRoute
  '/{-$locale}/gallery': typeof Char123LocaleChar125GalleryRoute
  '/{-$locale}/how-it-works': typeof Char123LocaleChar125HowItWorksRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/private-label-sup': typeof Char123LocaleChar125PrivateLabelSupRoute
  '/{-$locale}/search': typeof Char123LocaleChar125SearchRoute
  '/{-$locale}/solutions': typeof Char123LocaleChar125SolutionsRouteWithChildren
  '/{-$locale}/sup-for-clubs': typeof Char123LocaleChar125SupForClubsRoute
  '/{-$locale}/sup-for-resorts': typeof Char123LocaleChar125SupForResortsRoute
  '/{-$locale}/sup-startup-brands': typeof Char123LocaleChar125SupStartupBrandsRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/waitlist': typeof Char123LocaleChar125WaitlistRoute
  '/{-$locale}/who-we-serve': typeof Char123LocaleChar125WhoWeServeRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatars/$': typeof ApiAvatarsSplatRoute
  '/api/inquiry-logo/$': typeof ApiInquiryLogoSplatRoute
  '/{-$locale}/(auth)/forgot-password': typeof Char123LocaleChar125authForgotPasswordRoute
  '/{-$locale}/(auth)/login': typeof Char123LocaleChar125authLoginRoute
  '/{-$locale}/(auth)/register': typeof Char123LocaleChar125authRegisterRoute
  '/{-$locale}/(auth)/reset-password': typeof Char123LocaleChar125authResetPasswordRoute
  '/{-$locale}/(auth)/verify-email': typeof Char123LocaleChar125authVerifyEmailRoute
  '/{-$locale}/about/supsfactory-entity': typeof Char123LocaleChar125AboutSupsfactoryEntityRoute
  '/{-$locale}/admin/feedback': typeof Char123LocaleChar125AdminFeedbackRoute
  '/{-$locale}/admin/inquiries': typeof Char123LocaleChar125AdminInquiriesRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/{-$locale}/admin/waitlist': typeof Char123LocaleChar125AdminWaitlistRoute
  '/{-$locale}/app/account': typeof Char123LocaleChar125AppAccountRoute
  '/{-$locale}/app/feedback': typeof Char123LocaleChar125AppFeedbackRoute
  '/{-$locale}/knowledge/$slug': typeof Char123LocaleChar125KnowledgeSlugRoute
  '/{-$locale}/products/$series': typeof Char123LocaleChar125ProductsSeriesRoute
  '/{-$locale}/projects/$slug': typeof Char123LocaleChar125ProjectsSlugRoute
  '/{-$locale}/solutions/club-sup': typeof Char123LocaleChar125SolutionsClubSupRoute
  '/{-$locale}/solutions/custom-sup': typeof Char123LocaleChar125SolutionsCustomSupRoute
  '/{-$locale}/solutions/private-label-sup': typeof Char123LocaleChar125SolutionsPrivateLabelSupRoute
  '/{-$locale}/solutions/resort-sup': typeof Char123LocaleChar125SolutionsResortSupRoute
  '/{-$locale}/solutions/school-sup': typeof Char123LocaleChar125SolutionsSchoolSupRoute
  '/{-$locale}/about/': typeof Char123LocaleChar125AboutIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125AppIndexRoute
  '/{-$locale}/knowledge/': typeof Char123LocaleChar125KnowledgeIndexRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
  '/{-$locale}/projects/': typeof Char123LocaleChar125ProjectsIndexRoute
  '/{-$locale}/solutions/': typeof Char123LocaleChar125SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/$'
    | '/b2b-solutions-matrix'
    | '/entity.json'
    | '/factory'
    | '/faq'
    | '/fishing'
    | '/inflatable-vs-hardboard'
    | '/knowledge'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/new-brand-trial-order'
    | '/news'
    | '/odm-development'
    | '/oem-manufacturing'
    | '/oem-moq-guide'
    | '/oem-odm'
    | '/oem-paddle'
    | '/oem-trust-assurance'
    | '/partners'
    | '/product-development'
    | '/proof-center'
    | '/quality'
    | '/randdcenter'
    | '/robots.txt'
    | '/rss.xml'
    | '/search-index.json'
    | '/sitemap-es.xml'
    | '/sitemap-news.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/size-guide'
    | '/sup-oem-moq-lead-time'
    | '/technology'
    | '/tourism-recreation'
    | '/warranty'
    | '/what-is-sup'
    | '/{-$locale}/admin'
    | '/admin/inquiries.csv'
    | '/admin/waitlist.csv'
    | '/api/search'
    | '/docs-md/$'
    | '/docs/$'
    | '/{-$locale}/changelog'
    | '/{-$locale}/contact'
    | '/{-$locale}/custom-sup-development'
    | '/{-$locale}/custom-sup-manufacturing'
    | '/{-$locale}/customizer'
    | '/{-$locale}/gallery'
    | '/{-$locale}/how-it-works'
    | '/{-$locale}/privacy'
    | '/{-$locale}/private-label-sup'
    | '/{-$locale}/search'
    | '/{-$locale}/solutions'
    | '/{-$locale}/sup-for-clubs'
    | '/{-$locale}/sup-for-resorts'
    | '/{-$locale}/sup-startup-brands'
    | '/{-$locale}/terms'
    | '/{-$locale}/waitlist'
    | '/{-$locale}/who-we-serve'
    | '/{-$locale}/'
    | '/api/auth/$'
    | '/api/avatars/$'
    | '/api/inquiry-logo/$'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/register'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/verify-email'
    | '/{-$locale}/about/supsfactory-entity'
    | '/{-$locale}/admin/feedback'
    | '/{-$locale}/admin/inquiries'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/admin/waitlist'
    | '/{-$locale}/app/account'
    | '/{-$locale}/app/feedback'
    | '/{-$locale}/knowledge/$slug'
    | '/{-$locale}/products/$series'
    | '/{-$locale}/projects/$slug'
    | '/{-$locale}/solutions/club-sup'
    | '/{-$locale}/solutions/custom-sup'
    | '/{-$locale}/solutions/private-label-sup'
    | '/{-$locale}/solutions/resort-sup'
    | '/{-$locale}/solutions/school-sup'
    | '/{-$locale}/about/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/app/'
    | '/{-$locale}/knowledge/'
    | '/{-$locale}/products/'
    | '/{-$locale}/projects/'
    | '/{-$locale}/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/b2b-solutions-matrix'
    | '/entity.json'
    | '/factory'
    | '/faq'
    | '/fishing'
    | '/inflatable-vs-hardboard'
    | '/knowledge'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/new-brand-trial-order'
    | '/news'
    | '/odm-development'
    | '/oem-manufacturing'
    | '/oem-moq-guide'
    | '/oem-odm'
    | '/oem-paddle'
    | '/oem-trust-assurance'
    | '/partners'
    | '/product-development'
    | '/proof-center'
    | '/quality'
    | '/randdcenter'
    | '/robots.txt'
    | '/rss.xml'
    | '/search-index.json'
    | '/sitemap-es.xml'
    | '/sitemap-news.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/size-guide'
    | '/sup-oem-moq-lead-time'
    | '/technology'
    | '/tourism-recreation'
    | '/warranty'
    | '/what-is-sup'
    | '/admin/inquiries.csv'
    | '/admin/waitlist.csv'
    | '/api/search'
    | '/docs-md/$'
    | '/docs/$'
    | '/{-$locale}/changelog'
    | '/{-$locale}/contact'
    | '/{-$locale}/custom-sup-development'
    | '/{-$locale}/custom-sup-manufacturing'
    | '/{-$locale}/customizer'
    | '/{-$locale}/gallery'
    | '/{-$locale}/how-it-works'
    | '/{-$locale}/privacy'
    | '/{-$locale}/private-label-sup'
    | '/{-$locale}/search'
    | '/{-$locale}/sup-for-clubs'
    | '/{-$locale}/sup-for-resorts'
    | '/{-$locale}/sup-startup-brands'
    | '/{-$locale}/terms'
    | '/{-$locale}/waitlist'
    | '/{-$locale}/who-we-serve'
    | '/{-$locale}'
    | '/api/auth/$'
    | '/api/avatars/$'
    | '/api/inquiry-logo/$'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/register'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/verify-email'
    | '/{-$locale}/about/supsfactory-entity'
    | '/{-$locale}/admin/feedback'
    | '/{-$locale}/admin/inquiries'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/admin/waitlist'
    | '/{-$locale}/app/account'
    | '/{-$locale}/app/feedback'
    | '/{-$locale}/knowledge/$slug'
    | '/{-$locale}/products/$series'
    | '/{-$locale}/projects/$slug'
    | '/{-$locale}/solutions/club-sup'
    | '/{-$locale}/solutions/custom-sup'
    | '/{-$locale}/solutions/private-label-sup'
    | '/{-$locale}/solutions/resort-sup'
    | '/{-$locale}/solutions/school-sup'
    | '/{-$locale}/about'
    | '/{-$locale}/admin'
    | '/{-$locale}/app'
    | '/{-$locale}/knowledge'
    | '/{-$locale}/products'
    | '/{-$locale}/projects'
    | '/{-$locale}/solutions'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/$'
    | '/b2b-solutions-matrix'
    | '/entity.json'
    | '/factory'
    | '/faq'
    | '/fishing'
    | '/inflatable-vs-hardboard'
    | '/knowledge'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/new-brand-trial-order'
    | '/news'
    | '/odm-development'
    | '/oem-manufacturing'
    | '/oem-moq-guide'
    | '/oem-odm'
    | '/oem-paddle'
    | '/oem-trust-assurance'
    | '/partners'
    | '/product-development'
    | '/proof-center'
    | '/quality'
    | '/randdcenter'
    | '/robots.txt'
    | '/rss.xml'
    | '/search-index.json'
    | '/sitemap-es.xml'
    | '/sitemap-news.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/size-guide'
    | '/sup-oem-moq-lead-time'
    | '/technology'
    | '/tourism-recreation'
    | '/warranty'
    | '/what-is-sup'
    | '/{-$locale}/admin'
    | '/admin/inquiries.csv'
    | '/admin/waitlist.csv'
    | '/api/search'
    | '/docs-md/$'
    | '/docs/$'
    | '/{-$locale}/changelog'
    | '/{-$locale}/contact'
    | '/{-$locale}/custom-sup-development'
    | '/{-$locale}/custom-sup-manufacturing'
    | '/{-$locale}/customizer'
    | '/{-$locale}/gallery'
    | '/{-$locale}/how-it-works'
    | '/{-$locale}/privacy'
    | '/{-$locale}/private-label-sup'
    | '/{-$locale}/search'
    | '/{-$locale}/solutions'
    | '/{-$locale}/sup-for-clubs'
    | '/{-$locale}/sup-for-resorts'
    | '/{-$locale}/sup-startup-brands'
    | '/{-$locale}/terms'
    | '/{-$locale}/waitlist'
    | '/{-$locale}/who-we-serve'
    | '/{-$locale}/'
    | '/api/auth/$'
    | '/api/avatars/$'
    | '/api/inquiry-logo/$'
    | '/{-$locale}/(auth)/forgot-password'
    | '/{-$locale}/(auth)/login'
    | '/{-$locale}/(auth)/register'
    | '/{-$locale}/(auth)/reset-password'
    | '/{-$locale}/(auth)/verify-email'
    | '/{-$locale}/about/supsfactory-entity'
    | '/{-$locale}/admin/feedback'
    | '/{-$locale}/admin/inquiries'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/admin/waitlist'
    | '/{-$locale}/app/account'
    | '/{-$locale}/app/feedback'
    | '/{-$locale}/knowledge/$slug'
    | '/{-$locale}/products/$series'
    | '/{-$locale}/projects/$slug'
    | '/{-$locale}/solutions/club-sup'
    | '/{-$locale}/solutions/custom-sup'
    | '/{-$locale}/solutions/private-label-sup'
    | '/{-$locale}/solutions/resort-sup'
    | '/{-$locale}/solutions/school-sup'
    | '/{-$locale}/about/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/app/'
    | '/{-$locale}/knowledge/'
    | '/{-$locale}/products/'
    | '/{-$locale}/projects/'
    | '/{-$locale}/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  B2bSolutionsMatrixRoute: typeof B2bSolutionsMatrixRoute
  EntityDotjsonRoute: typeof EntityDotjsonRoute
  FactoryRoute: typeof FactoryRoute
  FaqRoute: typeof FaqRoute
  FishingRoute: typeof FishingRoute
  InflatableVsHardboardRoute: typeof InflatableVsHardboardRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NewBrandTrialOrderRoute: typeof NewBrandTrialOrderRoute
  NewsRoute: typeof NewsRoute
  OdmDevelopmentRoute: typeof OdmDevelopmentRoute
  OemManufacturingRoute: typeof OemManufacturingRoute
  OemMoqGuideRoute: typeof OemMoqGuideRoute
  OemOdmRoute: typeof OemOdmRoute
  OemPaddleRoute: typeof OemPaddleRoute
  OemTrustAssuranceRoute: typeof OemTrustAssuranceRoute
  PartnersRoute: typeof PartnersRoute
  ProductDevelopmentRoute: typeof ProductDevelopmentRoute
  ProofCenterRoute: typeof ProofCenterRoute
  QualityRoute: typeof QualityRoute
  RanddcenterRoute: typeof RanddcenterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SearchIndexDotjsonRoute: typeof SearchIndexDotjsonRoute
  SitemapEsDotxmlRoute: typeof SitemapEsDotxmlRoute
  SitemapNewsDotxmlRoute: typeof SitemapNewsDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapProductsDotxmlRoute: typeof SitemapProductsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SizeGuideRoute: typeof SizeGuideRoute
  SupOemMoqLeadTimeRoute: typeof SupOemMoqLeadTimeRoute
  TechnologyRoute: typeof TechnologyRoute
  TourismRecreationRoute: typeof TourismRecreationRoute
  WarrantyRoute: typeof WarrantyRoute
  WhatIsSupRoute: typeof WhatIsSupRoute
  AdminInquiriesDotcsvRoute: typeof AdminInquiriesDotcsvRoute
  AdminWaitlistDotcsvRoute: typeof AdminWaitlistDotcsvRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsMdSplatRoute: typeof DocsMdSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAvatarsSplatRoute: typeof ApiAvatarsSplatRoute
  ApiInquiryLogoSplatRoute: typeof ApiInquiryLogoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-sup': {
      id: '/what-is-sup'
      path: '/what-is-sup'
      fullPath: '/what-is-sup'
      preLoaderRoute: typeof WhatIsSupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourism-recreation': {
      id: '/tourism-recreation'
      path: '/tourism-recreation'
      fullPath: '/tourism-recreation'
      preLoaderRoute: typeof TourismRecreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sup-oem-moq-lead-time': {
      id: '/sup-oem-moq-lead-time'
      path: '/sup-oem-moq-lead-time'
      fullPath: '/sup-oem-moq-lead-time'
      preLoaderRoute: typeof SupOemMoqLeadTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-products.xml': {
      id: '/sitemap-products.xml'
      path: '/sitemap-products.xml'
      fullPath: '/sitemap-products.xml'
      preLoaderRoute: typeof SitemapProductsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-news.xml': {
      id: '/sitemap-news.xml'
      path: '/sitemap-news.xml'
      fullPath: '/sitemap-news.xml'
      preLoaderRoute: typeof SitemapNewsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-es.xml': {
      id: '/sitemap-es.xml'
      path: '/sitemap-es.xml'
      fullPath: '/sitemap-es.xml'
      preLoaderRoute: typeof SitemapEsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-index.json': {
      id: '/search-index.json'
      path: '/search-index.json'
      fullPath: '/search-index.json'
      preLoaderRoute: typeof SearchIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randdcenter': {
      id: '/randdcenter'
      path: '/randdcenter'
      fullPath: '/randdcenter'
      preLoaderRoute: typeof RanddcenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-center': {
      id: '/proof-center'
      path: '/proof-center'
      fullPath: '/proof-center'
      preLoaderRoute: typeof ProofCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-development': {
      id: '/product-development'
      path: '/product-development'
      fullPath: '/product-development'
      preLoaderRoute: typeof ProductDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oem-trust-assurance': {
      id: '/oem-trust-assurance'
      path: '/oem-trust-assurance'
      fullPath: '/oem-trust-assurance'
      preLoaderRoute: typeof OemTrustAssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oem-paddle': {
      id: '/oem-paddle'
      path: '/oem-paddle'
      fullPath: '/oem-paddle'
      preLoaderRoute: typeof OemPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oem-odm': {
      id: '/oem-odm'
      path: '/oem-odm'
      fullPath: '/oem-odm'
      preLoaderRoute: typeof OemOdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oem-moq-guide': {
      id: '/oem-moq-guide'
      path: '/oem-moq-guide'
      fullPath: '/oem-moq-guide'
      preLoaderRoute: typeof OemMoqGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oem-manufacturing': {
      id: '/oem-manufacturing'
      path: '/oem-manufacturing'
      fullPath: '/oem-manufacturing'
      preLoaderRoute: typeof OemManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odm-development': {
      id: '/odm-development'
      path: '/odm-development'
      fullPath: '/odm-development'
      preLoaderRoute: typeof OdmDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-brand-trial-order': {
      id: '/new-brand-trial-order'
      path: '/new-brand-trial-order'
      fullPath: '/new-brand-trial-order'
      preLoaderRoute: typeof NewBrandTrialOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inflatable-vs-hardboard': {
      id: '/inflatable-vs-hardboard'
      path: '/inflatable-vs-hardboard'
      fullPath: '/inflatable-vs-hardboard'
      preLoaderRoute: typeof InflatableVsHardboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fishing': {
      id: '/fishing'
      path: '/fishing'
      fullPath: '/fishing'
      preLoaderRoute: typeof FishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity.json': {
      id: '/entity.json'
      path: '/entity.json'
      fullPath: '/entity.json'
      preLoaderRoute: typeof EntityDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b-solutions-matrix': {
      id: '/b2b-solutions-matrix'
      path: '/b2b-solutions-matrix'
      fullPath: '/b2b-solutions-matrix'
      preLoaderRoute: typeof B2bSolutionsMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/who-we-serve': {
      id: '/{-$locale}/who-we-serve'
      path: '/who-we-serve'
      fullPath: '/{-$locale}/who-we-serve'
      preLoaderRoute: typeof Char123LocaleChar125WhoWeServeRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/waitlist': {
      id: '/{-$locale}/waitlist'
      path: '/waitlist'
      fullPath: '/{-$locale}/waitlist'
      preLoaderRoute: typeof Char123LocaleChar125WaitlistRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/sup-startup-brands': {
      id: '/{-$locale}/sup-startup-brands'
      path: '/sup-startup-brands'
      fullPath: '/{-$locale}/sup-startup-brands'
      preLoaderRoute: typeof Char123LocaleChar125SupStartupBrandsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/sup-for-resorts': {
      id: '/{-$locale}/sup-for-resorts'
      path: '/sup-for-resorts'
      fullPath: '/{-$locale}/sup-for-resorts'
      preLoaderRoute: typeof Char123LocaleChar125SupForResortsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/sup-for-clubs': {
      id: '/{-$locale}/sup-for-clubs'
      path: '/sup-for-clubs'
      fullPath: '/{-$locale}/sup-for-clubs'
      preLoaderRoute: typeof Char123LocaleChar125SupForClubsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/solutions': {
      id: '/{-$locale}/solutions'
      path: '/solutions'
      fullPath: '/{-$locale}/solutions'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/search': {
      id: '/{-$locale}/search'
      path: '/search'
      fullPath: '/{-$locale}/search'
      preLoaderRoute: typeof Char123LocaleChar125SearchRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/private-label-sup': {
      id: '/{-$locale}/private-label-sup'
      path: '/private-label-sup'
      fullPath: '/{-$locale}/private-label-sup'
      preLoaderRoute: typeof Char123LocaleChar125PrivateLabelSupRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/how-it-works': {
      id: '/{-$locale}/how-it-works'
      path: '/how-it-works'
      fullPath: '/{-$locale}/how-it-works'
      preLoaderRoute: typeof Char123LocaleChar125HowItWorksRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/gallery': {
      id: '/{-$locale}/gallery'
      path: '/gallery'
      fullPath: '/{-$locale}/gallery'
      preLoaderRoute: typeof Char123LocaleChar125GalleryRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/customizer': {
      id: '/{-$locale}/customizer'
      path: '/customizer'
      fullPath: '/{-$locale}/customizer'
      preLoaderRoute: typeof Char123LocaleChar125CustomizerRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/custom-sup-manufacturing': {
      id: '/{-$locale}/custom-sup-manufacturing'
      path: '/custom-sup-manufacturing'
      fullPath: '/{-$locale}/custom-sup-manufacturing'
      preLoaderRoute: typeof Char123LocaleChar125CustomSupManufacturingRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/custom-sup-development': {
      id: '/{-$locale}/custom-sup-development'
      path: '/custom-sup-development'
      fullPath: '/{-$locale}/custom-sup-development'
      preLoaderRoute: typeof Char123LocaleChar125CustomSupDevelopmentRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/changelog': {
      id: '/{-$locale}/changelog'
      path: '/changelog'
      fullPath: '/{-$locale}/changelog'
      preLoaderRoute: typeof Char123LocaleChar125ChangelogRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-md/$': {
      id: '/docs-md/$'
      path: '/docs-md/$'
      fullPath: '/docs-md/$'
      preLoaderRoute: typeof DocsMdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlist.csv': {
      id: '/admin/waitlist.csv'
      path: '/admin/waitlist.csv'
      fullPath: '/admin/waitlist.csv'
      preLoaderRoute: typeof AdminWaitlistDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries.csv': {
      id: '/admin/inquiries.csv'
      path: '/admin/inquiries.csv'
      fullPath: '/admin/inquiries.csv'
      preLoaderRoute: typeof AdminInquiriesDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/admin': {
      id: '/{-$locale}/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125AdminRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/solutions/': {
      id: '/{-$locale}/solutions/'
      path: '/'
      fullPath: '/{-$locale}/solutions/'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125SolutionsRoute
    }
    '/{-$locale}/projects/': {
      id: '/{-$locale}/projects/'
      path: '/projects'
      fullPath: '/{-$locale}/projects/'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/products/': {
      id: '/{-$locale}/products/'
      path: '/products'
      fullPath: '/{-$locale}/products/'
      preLoaderRoute: typeof Char123LocaleChar125ProductsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/knowledge/': {
      id: '/{-$locale}/knowledge/'
      path: '/knowledge'
      fullPath: '/{-$locale}/knowledge/'
      preLoaderRoute: typeof Char123LocaleChar125KnowledgeIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/app/': {
      id: '/{-$locale}/app/'
      path: '/app'
      fullPath: '/{-$locale}/app/'
      preLoaderRoute: typeof Char123LocaleChar125AppIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/admin/': {
      id: '/{-$locale}/admin/'
      path: '/'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125AdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/about/': {
      id: '/{-$locale}/about/'
      path: '/about'
      fullPath: '/{-$locale}/about/'
      preLoaderRoute: typeof Char123LocaleChar125AboutIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/solutions/school-sup': {
      id: '/{-$locale}/solutions/school-sup'
      path: '/school-sup'
      fullPath: '/{-$locale}/solutions/school-sup'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsSchoolSupRouteImport
      parentRoute: typeof Char123LocaleChar125SolutionsRoute
    }
    '/{-$locale}/solutions/resort-sup': {
      id: '/{-$locale}/solutions/resort-sup'
      path: '/resort-sup'
      fullPath: '/{-$locale}/solutions/resort-sup'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsResortSupRouteImport
      parentRoute: typeof Char123LocaleChar125SolutionsRoute
    }
    '/{-$locale}/solutions/private-label-sup': {
      id: '/{-$locale}/solutions/private-label-sup'
      path: '/private-label-sup'
      fullPath: '/{-$locale}/solutions/private-label-sup'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsPrivateLabelSupRouteImport
      parentRoute: typeof Char123LocaleChar125SolutionsRoute
    }
    '/{-$locale}/solutions/custom-sup': {
      id: '/{-$locale}/solutions/custom-sup'
      path: '/custom-sup'
      fullPath: '/{-$locale}/solutions/custom-sup'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsCustomSupRouteImport
      parentRoute: typeof Char123LocaleChar125SolutionsRoute
    }
    '/{-$locale}/solutions/club-sup': {
      id: '/{-$locale}/solutions/club-sup'
      path: '/club-sup'
      fullPath: '/{-$locale}/solutions/club-sup'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsClubSupRouteImport
      parentRoute: typeof Char123LocaleChar125SolutionsRoute
    }
    '/{-$locale}/projects/$slug': {
      id: '/{-$locale}/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/{-$locale}/projects/$slug'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsSlugRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/products/$series': {
      id: '/{-$locale}/products/$series'
      path: '/products/$series'
      fullPath: '/{-$locale}/products/$series'
      preLoaderRoute: typeof Char123LocaleChar125ProductsSeriesRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/knowledge/$slug': {
      id: '/{-$locale}/knowledge/$slug'
      path: '/knowledge/$slug'
      fullPath: '/{-$locale}/knowledge/$slug'
      preLoaderRoute: typeof Char123LocaleChar125KnowledgeSlugRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/app/feedback': {
      id: '/{-$locale}/app/feedback'
      path: '/app/feedback'
      fullPath: '/{-$locale}/app/feedback'
      preLoaderRoute: typeof Char123LocaleChar125AppFeedbackRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/app/account': {
      id: '/{-$locale}/app/account'
      path: '/app/account'
      fullPath: '/{-$locale}/app/account'
      preLoaderRoute: typeof Char123LocaleChar125AppAccountRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/admin/waitlist': {
      id: '/{-$locale}/admin/waitlist'
      path: '/waitlist'
      fullPath: '/{-$locale}/admin/waitlist'
      preLoaderRoute: typeof Char123LocaleChar125AdminWaitlistRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/admin/users': {
      id: '/{-$locale}/admin/users'
      path: '/users'
      fullPath: '/{-$locale}/admin/users'
      preLoaderRoute: typeof Char123LocaleChar125AdminUsersRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/admin/inquiries': {
      id: '/{-$locale}/admin/inquiries'
      path: '/inquiries'
      fullPath: '/{-$locale}/admin/inquiries'
      preLoaderRoute: typeof Char123LocaleChar125AdminInquiriesRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/admin/feedback': {
      id: '/{-$locale}/admin/feedback'
      path: '/feedback'
      fullPath: '/{-$locale}/admin/feedback'
      preLoaderRoute: typeof Char123LocaleChar125AdminFeedbackRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/about/supsfactory-entity': {
      id: '/{-$locale}/about/supsfactory-entity'
      path: '/about/supsfactory-entity'
      fullPath: '/{-$locale}/about/supsfactory-entity'
      preLoaderRoute: typeof Char123LocaleChar125AboutSupsfactoryEntityRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)/verify-email': {
      id: '/{-$locale}/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/{-$locale}/verify-email'
      preLoaderRoute: typeof Char123LocaleChar125authVerifyEmailRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)/reset-password': {
      id: '/{-$locale}/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/{-$locale}/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125authResetPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)/register': {
      id: '/{-$locale}/(auth)/register'
      path: '/register'
      fullPath: '/{-$locale}/register'
      preLoaderRoute: typeof Char123LocaleChar125authRegisterRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)/login': {
      id: '/{-$locale}/(auth)/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125authLoginRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)/forgot-password': {
      id: '/{-$locale}/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/{-$locale}/forgot-password'
      preLoaderRoute: typeof Char123LocaleChar125authForgotPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/api/inquiry-logo/$': {
      id: '/api/inquiry-logo/$'
      path: '/api/inquiry-logo/$'
      fullPath: '/api/inquiry-logo/$'
      preLoaderRoute: typeof ApiInquiryLogoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatars/$': {
      id: '/api/avatars/$'
      path: '/api/avatars/$'
      fullPath: '/api/avatars/$'
      preLoaderRoute: typeof ApiAvatarsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125AdminRouteRouteChildren {
  Char123LocaleChar125AdminFeedbackRoute: typeof Char123LocaleChar125AdminFeedbackRoute
  Char123LocaleChar125AdminInquiriesRoute: typeof Char123LocaleChar125AdminInquiriesRoute
  Char123LocaleChar125AdminUsersRoute: typeof Char123LocaleChar125AdminUsersRoute
  Char123LocaleChar125AdminWaitlistRoute: typeof Char123LocaleChar125AdminWaitlistRoute
  Char123LocaleChar125AdminIndexRoute: typeof Char123LocaleChar125AdminIndexRoute
}

const Char123LocaleChar125AdminRouteRouteChildren: Char123LocaleChar125AdminRouteRouteChildren =
  {
    Char123LocaleChar125AdminFeedbackRoute:
      Char123LocaleChar125AdminFeedbackRoute,
    Char123LocaleChar125AdminInquiriesRoute:
      Char123LocaleChar125AdminInquiriesRoute,
    Char123LocaleChar125AdminUsersRoute: Char123LocaleChar125AdminUsersRoute,
    Char123LocaleChar125AdminWaitlistRoute:
      Char123LocaleChar125AdminWaitlistRoute,
    Char123LocaleChar125AdminIndexRoute: Char123LocaleChar125AdminIndexRoute,
  }

const Char123LocaleChar125AdminRouteRouteWithChildren =
  Char123LocaleChar125AdminRouteRoute._addFileChildren(
    Char123LocaleChar125AdminRouteRouteChildren,
  )

interface Char123LocaleChar125SolutionsRouteChildren {
  Char123LocaleChar125SolutionsClubSupRoute: typeof Char123LocaleChar125SolutionsClubSupRoute
  Char123LocaleChar125SolutionsCustomSupRoute: typeof Char123LocaleChar125SolutionsCustomSupRoute
  Char123LocaleChar125SolutionsPrivateLabelSupRoute: typeof Char123LocaleChar125SolutionsPrivateLabelSupRoute
  Char123LocaleChar125SolutionsResortSupRoute: typeof Char123LocaleChar125SolutionsResortSupRoute
  Char123LocaleChar125SolutionsSchoolSupRoute: typeof Char123LocaleChar125SolutionsSchoolSupRoute
  Char123LocaleChar125SolutionsIndexRoute: typeof Char123LocaleChar125SolutionsIndexRoute
}

const Char123LocaleChar125SolutionsRouteChildren: Char123LocaleChar125SolutionsRouteChildren =
  {
    Char123LocaleChar125SolutionsClubSupRoute:
      Char123LocaleChar125SolutionsClubSupRoute,
    Char123LocaleChar125SolutionsCustomSupRoute:
      Char123LocaleChar125SolutionsCustomSupRoute,
    Char123LocaleChar125SolutionsPrivateLabelSupRoute:
      Char123LocaleChar125SolutionsPrivateLabelSupRoute,
    Char123LocaleChar125SolutionsResortSupRoute:
      Char123LocaleChar125SolutionsResortSupRoute,
    Char123LocaleChar125SolutionsSchoolSupRoute:
      Char123LocaleChar125SolutionsSchoolSupRoute,
    Char123LocaleChar125SolutionsIndexRoute:
      Char123LocaleChar125SolutionsIndexRoute,
  }

const Char123LocaleChar125SolutionsRouteWithChildren =
  Char123LocaleChar125SolutionsRoute._addFileChildren(
    Char123LocaleChar125SolutionsRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AdminRouteRoute: typeof Char123LocaleChar125AdminRouteRouteWithChildren
  Char123LocaleChar125ChangelogRoute: typeof Char123LocaleChar125ChangelogRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125CustomSupDevelopmentRoute: typeof Char123LocaleChar125CustomSupDevelopmentRoute
  Char123LocaleChar125CustomSupManufacturingRoute: typeof Char123LocaleChar125CustomSupManufacturingRoute
  Char123LocaleChar125CustomizerRoute: typeof Char123LocaleChar125CustomizerRoute
  Char123LocaleChar125GalleryRoute: typeof Char123LocaleChar125GalleryRoute
  Char123LocaleChar125HowItWorksRoute: typeof Char123LocaleChar125HowItWorksRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125PrivateLabelSupRoute: typeof Char123LocaleChar125PrivateLabelSupRoute
  Char123LocaleChar125SearchRoute: typeof Char123LocaleChar125SearchRoute
  Char123LocaleChar125SolutionsRoute: typeof Char123LocaleChar125SolutionsRouteWithChildren
  Char123LocaleChar125SupForClubsRoute: typeof Char123LocaleChar125SupForClubsRoute
  Char123LocaleChar125SupForResortsRoute: typeof Char123LocaleChar125SupForResortsRoute
  Char123LocaleChar125SupStartupBrandsRoute: typeof Char123LocaleChar125SupStartupBrandsRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125WaitlistRoute: typeof Char123LocaleChar125WaitlistRoute
  Char123LocaleChar125WhoWeServeRoute: typeof Char123LocaleChar125WhoWeServeRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125authForgotPasswordRoute: typeof Char123LocaleChar125authForgotPasswordRoute
  Char123LocaleChar125authLoginRoute: typeof Char123LocaleChar125authLoginRoute
  Char123LocaleChar125authRegisterRoute: typeof Char123LocaleChar125authRegisterRoute
  Char123LocaleChar125authResetPasswordRoute: typeof Char123LocaleChar125authResetPasswordRoute
  Char123LocaleChar125authVerifyEmailRoute: typeof Char123LocaleChar125authVerifyEmailRoute
  Char123LocaleChar125AboutSupsfactoryEntityRoute: typeof Char123LocaleChar125AboutSupsfactoryEntityRoute
  Char123LocaleChar125AppAccountRoute: typeof Char123LocaleChar125AppAccountRoute
  Char123LocaleChar125AppFeedbackRoute: typeof Char123LocaleChar125AppFeedbackRoute
  Char123LocaleChar125KnowledgeSlugRoute: typeof Char123LocaleChar125KnowledgeSlugRoute
  Char123LocaleChar125ProductsSeriesRoute: typeof Char123LocaleChar125ProductsSeriesRoute
  Char123LocaleChar125ProjectsSlugRoute: typeof Char123LocaleChar125ProjectsSlugRoute
  Char123LocaleChar125AboutIndexRoute: typeof Char123LocaleChar125AboutIndexRoute
  Char123LocaleChar125AppIndexRoute: typeof Char123LocaleChar125AppIndexRoute
  Char123LocaleChar125KnowledgeIndexRoute: typeof Char123LocaleChar125KnowledgeIndexRoute
  Char123LocaleChar125ProductsIndexRoute: typeof Char123LocaleChar125ProductsIndexRoute
  Char123LocaleChar125ProjectsIndexRoute: typeof Char123LocaleChar125ProjectsIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AdminRouteRoute:
      Char123LocaleChar125AdminRouteRouteWithChildren,
    Char123LocaleChar125ChangelogRoute: Char123LocaleChar125ChangelogRoute,
    Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
    Char123LocaleChar125CustomSupDevelopmentRoute:
      Char123LocaleChar125CustomSupDevelopmentRoute,
    Char123LocaleChar125CustomSupManufacturingRoute:
      Char123LocaleChar125CustomSupManufacturingRoute,
    Char123LocaleChar125CustomizerRoute: Char123LocaleChar125CustomizerRoute,
    Char123LocaleChar125GalleryRoute: Char123LocaleChar125GalleryRoute,
    Char123LocaleChar125HowItWorksRoute: Char123LocaleChar125HowItWorksRoute,
    Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
    Char123LocaleChar125PrivateLabelSupRoute:
      Char123LocaleChar125PrivateLabelSupRoute,
    Char123LocaleChar125SearchRoute: Char123LocaleChar125SearchRoute,
    Char123LocaleChar125SolutionsRoute:
      Char123LocaleChar125SolutionsRouteWithChildren,
    Char123LocaleChar125SupForClubsRoute: Char123LocaleChar125SupForClubsRoute,
    Char123LocaleChar125SupForResortsRoute:
      Char123LocaleChar125SupForResortsRoute,
    Char123LocaleChar125SupStartupBrandsRoute:
      Char123LocaleChar125SupStartupBrandsRoute,
    Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
    Char123LocaleChar125WaitlistRoute: Char123LocaleChar125WaitlistRoute,
    Char123LocaleChar125WhoWeServeRoute: Char123LocaleChar125WhoWeServeRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125authForgotPasswordRoute:
      Char123LocaleChar125authForgotPasswordRoute,
    Char123LocaleChar125authLoginRoute: Char123LocaleChar125authLoginRoute,
    Char123LocaleChar125authRegisterRoute:
      Char123LocaleChar125authRegisterRoute,
    Char123LocaleChar125authResetPasswordRoute:
      Char123LocaleChar125authResetPasswordRoute,
    Char123LocaleChar125authVerifyEmailRoute:
      Char123LocaleChar125authVerifyEmailRoute,
    Char123LocaleChar125AboutSupsfactoryEntityRoute:
      Char123LocaleChar125AboutSupsfactoryEntityRoute,
    Char123LocaleChar125AppAccountRoute: Char123LocaleChar125AppAccountRoute,
    Char123LocaleChar125AppFeedbackRoute: Char123LocaleChar125AppFeedbackRoute,
    Char123LocaleChar125KnowledgeSlugRoute:
      Char123LocaleChar125KnowledgeSlugRoute,
    Char123LocaleChar125ProductsSeriesRoute:
      Char123LocaleChar125ProductsSeriesRoute,
    Char123LocaleChar125ProjectsSlugRoute:
      Char123LocaleChar125ProjectsSlugRoute,
    Char123LocaleChar125AboutIndexRoute: Char123LocaleChar125AboutIndexRoute,
    Char123LocaleChar125AppIndexRoute: Char123LocaleChar125AppIndexRoute,
    Char123LocaleChar125KnowledgeIndexRoute:
      Char123LocaleChar125KnowledgeIndexRoute,
    Char123LocaleChar125ProductsIndexRoute:
      Char123LocaleChar125ProductsIndexRoute,
    Char123LocaleChar125ProjectsIndexRoute:
      Char123LocaleChar125ProjectsIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  SplatRoute: SplatRoute,
  B2bSolutionsMatrixRoute: B2bSolutionsMatrixRoute,
  EntityDotjsonRoute: EntityDotjsonRoute,
  FactoryRoute: FactoryRoute,
  FaqRoute: FaqRoute,
  FishingRoute: FishingRoute,
  InflatableVsHardboardRoute: InflatableVsHardboardRoute,
  KnowledgeRoute: KnowledgeRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NewBrandTrialOrderRoute: NewBrandTrialOrderRoute,
  NewsRoute: NewsRoute,
  OdmDevelopmentRoute: OdmDevelopmentRoute,
  OemManufacturingRoute: OemManufacturingRoute,
  OemMoqGuideRoute: OemMoqGuideRoute,
  OemOdmRoute: OemOdmRoute,
  OemPaddleRoute: OemPaddleRoute,
  OemTrustAssuranceRoute: OemTrustAssuranceRoute,
  PartnersRoute: PartnersRoute,
  ProductDevelopmentRoute: ProductDevelopmentRoute,
  ProofCenterRoute: ProofCenterRoute,
  QualityRoute: QualityRoute,
  RanddcenterRoute: RanddcenterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SearchIndexDotjsonRoute: SearchIndexDotjsonRoute,
  SitemapEsDotxmlRoute: SitemapEsDotxmlRoute,
  SitemapNewsDotxmlRoute: SitemapNewsDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapProductsDotxmlRoute: SitemapProductsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SizeGuideRoute: SizeGuideRoute,
  SupOemMoqLeadTimeRoute: SupOemMoqLeadTimeRoute,
  TechnologyRoute: TechnologyRoute,
  TourismRecreationRoute: TourismRecreationRoute,
  WarrantyRoute: WarrantyRoute,
  WhatIsSupRoute: WhatIsSupRoute,
  AdminInquiriesDotcsvRoute: AdminInquiriesDotcsvRoute,
  AdminWaitlistDotcsvRoute: AdminWaitlistDotcsvRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsMdSplatRoute: DocsMdSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAvatarsSplatRoute: ApiAvatarsSplatRoute,
  ApiInquiryLogoSplatRoute: ApiInquiryLogoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
