/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125WhoWeServeRouteImport } from './routes/{-$locale}/who-we-serve'
import { Route as Char123LocaleChar125WaitlistRouteImport } from './routes/{-$locale}/waitlist'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125SupStartupBrandsRouteImport } from './routes/{-$locale}/sup-startup-brands'
import { Route as Char123LocaleChar125SupForResortsRouteImport } from './routes/{-$locale}/sup-for-resorts'
import { Route as Char123LocaleChar125SupForClubsRouteImport } from './routes/{-$locale}/sup-for-clubs'
import { Route as Char123LocaleChar125SponsorRouteImport } from './routes/{-$locale}/sponsor'
import { Route as Char123LocaleChar125SolutionsRouteImport } from './routes/{-$locale}/solutions'
import { Route as Char123LocaleChar125ProductsRouteImport } from './routes/{-$locale}/products'
import { Route as Char123LocaleChar125PrivateLabelSupRouteImport } from './routes/{-$locale}/private-label-sup'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}/privacy'
import { Route as Char123LocaleChar125PricingRouteImport } from './routes/{-$locale}/pricing'
import { Route as Char123LocaleChar125HowItWorksRouteImport } from './routes/{-$locale}/how-it-works'
import { Route as Char123LocaleChar125GalleryRouteImport } from './routes/{-$locale}/gallery'
import { Route as Char123LocaleChar125CustomizerRouteImport } from './routes/{-$locale}/customizer'
import { Route as Char123LocaleChar125CustomSupManufacturingRouteImport } from './routes/{-$locale}/custom-sup-manufacturing'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125ChangelogRouteImport } from './routes/{-$locale}/changelog'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsMdSplatRouteImport } from './routes/docs-md/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AdminWaitlistDotcsvRouteImport } from './routes/admin/waitlist[.]csv'
import { Route as AdminSponsorsDotcsvRouteImport } from './routes/admin/sponsors[.]csv'
import { Route as AdminInquiriesDotcsvRouteImport } from './routes/admin/inquiries[.]csv'
import { Route as Char123LocaleChar125AdminRouteRouteImport } from './routes/{-$locale}/admin/route'
import { Route as Char123LocaleChar125AppIndexRouteImport } from './routes/{-$locale}/app/index'
import { Route as Char123LocaleChar125AdminIndexRouteImport } from './routes/{-$locale}/admin/index'
import { Route as Char123LocaleChar125AppProRouteImport } from './routes/{-$locale}/app/pro'
import { Route as Char123LocaleChar125AppFeedbackRouteImport } from './routes/{-$locale}/app/feedback'
import { Route as Char123LocaleChar125AppAccountRouteImport } from './routes/{-$locale}/app/account'
import { Route as Char123LocaleChar125AdminWaitlistRouteImport } from './routes/{-$locale}/admin/waitlist'
import { Route as Char123LocaleChar125AdminUsersRouteImport } from './routes/{-$locale}/admin/users'
import { Route as Char123LocaleChar125AdminSponsorsRouteImport } from './routes/{-$locale}/admin/sponsors'
import { Route as Char123LocaleChar125AdminInquiriesRouteImport } from './routes/{-$locale}/admin/inquiries'
import { Route as Char123LocaleChar125AdminFeedbackRouteImport } from './routes/{-$locale}/admin/feedback'
import { Route as Char123LocaleChar125authVerifyEmailRouteImport } from './routes/{-$locale}/(auth)/verify-email'
import { Route as Char123LocaleChar125authResetPasswordRouteImport } from './routes/{-$locale}/(auth)/reset-password'
import { Route as Char123LocaleChar125authRegisterRouteImport } from './routes/{-$locale}/(auth)/register'
import { Route as Char123LocaleChar125authLoginRouteImport } from './routes/{-$locale}/(auth)/login'
import { Route as Char123LocaleChar125authForgotPasswordRouteImport } from './routes/{-$locale}/(auth)/forgot-password'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiInquiryLogoSplatRouteImport } from './routes/api/inquiry-logo/$'
import { Route as ApiAvatarsSplatRouteImport } from './routes/api/avatars/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125WhoWeServeRoute =
  Char123LocaleChar125WhoWeServeRouteImport.update({
    id: '/who-we-serve',
    path: '/who-we-serve',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125WaitlistRoute =
  Char123LocaleChar125WaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SupStartupBrandsRoute =
  Char123LocaleChar125SupStartupBrandsRouteImport.update({
    id: '/sup-startup-brands',
    path: '/sup-startup-brands',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SupForResortsRoute =
  Char123LocaleChar125SupForResortsRouteImport.update({
    id: '/sup-for-resorts',
    path: '/sup-for-resorts',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SupForClubsRoute =
  Char123LocaleChar125SupForClubsRouteImport.update({
    id: '/sup-for-clubs',
    path: '/sup-for-clubs',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SponsorRoute =
  Char123LocaleChar125SponsorRouteImport.update({
    id: '/sponsor',
    path: '/sponsor',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SolutionsRoute =
  Char123LocaleChar125SolutionsRouteImport.update({
    id: '/solutions',
    path: '/solutions',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ProductsRoute =
  Char123LocaleChar125ProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PrivateLabelSupRoute =
  Char123LocaleChar125PrivateLabelSupRouteImport.update({
    id: '/private-label-sup',
    path: '/private-label-sup',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PricingRoute =
  Char123LocaleChar125PricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125HowItWorksRoute =
  Char123LocaleChar125HowItWorksRouteImport.update({
    id: '/how-it-works',
    path: '/how-it-works',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125GalleryRoute =
  Char123LocaleChar125GalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CustomizerRoute =
  Char123LocaleChar125CustomizerRouteImport.update({
    id: '/customizer',
    path: '/customizer',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CustomSupManufacturingRoute =
  Char123LocaleChar125CustomSupManufacturingRouteImport.update({
    id: '/custom-sup-manufacturing',
    path: '/custom-sup-manufacturing',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ChangelogRoute =
  Char123LocaleChar125ChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMdSplatRoute = DocsMdSplatRouteImport.update({
  id: '/docs-md/$',
  path: '/docs-md/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistDotcsvRoute = AdminWaitlistDotcsvRouteImport.update({
  id: '/admin/waitlist.csv',
  path: '/admin/waitlist.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsDotcsvRoute = AdminSponsorsDotcsvRouteImport.update({
  id: '/admin/sponsors.csv',
  path: '/admin/sponsors.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesDotcsvRoute = AdminInquiriesDotcsvRouteImport.update({
  id: '/admin/inquiries.csv',
  path: '/admin/inquiries.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AdminRouteRoute =
  Char123LocaleChar125AdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppIndexRoute =
  Char123LocaleChar125AppIndexRouteImport.update({
    id: '/app/',
    path: '/app/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AdminIndexRoute =
  Char123LocaleChar125AdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AppProRoute =
  Char123LocaleChar125AppProRouteImport.update({
    id: '/app/pro',
    path: '/app/pro',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppFeedbackRoute =
  Char123LocaleChar125AppFeedbackRouteImport.update({
    id: '/app/feedback',
    path: '/app/feedback',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppAccountRoute =
  Char123LocaleChar125AppAccountRouteImport.update({
    id: '/app/account',
    path: '/app/account',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AdminWaitlistRoute =
  Char123LocaleChar125AdminWaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AdminUsersRoute =
  Char123LocaleChar125AdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AdminSponsorsRoute =
  Char123LocaleChar125AdminSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AdminInquiriesRoute =
  Char123LocaleChar125AdminInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AdminFeedbackRoute =
  Char123LocaleChar125AdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125authVerifyEmailRoute =
  Char123LocaleChar125authVerifyEmailRouteImport.update({
    id: '/(auth)/verify-email',
    path: '/verify-email',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authResetPasswordRoute =
  Char123LocaleChar125authResetPasswordRouteImport.update({
    id: '/(auth)/reset-password',
    path: '/reset-password',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authRegisterRoute =
  Char123LocaleChar125authRegisterRouteImport.update({
    id: '/(auth)/register',
    path: '/register',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authLoginRoute =
  Char123LocaleChar125authLoginRouteImport.update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authForgotPasswordRoute =
  Char123LocaleChar125authForgotPasswordRouteImport.update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquiryLogoSplatRoute = ApiInquiryLogoSplatRouteImport.update({
  id: '/api/inquiry-logo/$',
  path: '/api/inquiry-logo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarsSplatRoute = ApiAvatarsSplatRouteImport.update({
  id: '/api/avatars/$',
  path: '/api/avatars/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRouteRouteWithChildren
  '/admin/inquiries.csv': typeof AdminInquiriesDotcsvRoute
  '/admin/sponsors.csv': typeof AdminSponsorsDotcsvRoute
  '/admin/waitlist.csv': typeof AdminWaitlistDotcsvRoute
  '/api/search': typeof ApiSearchRoute
  '/docs-md/$': typeof DocsMdSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125ChangelogRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/custom-sup-manufacturing': typeof Char123LocaleChar125CustomSupManufacturingRoute
  '/{-$locale}/customizer': typeof Char123LocaleChar125CustomizerRoute
  '/{-$locale}/gallery': typeof Char123LocaleChar125GalleryRoute
  '/{-$locale}/how-it-works': typeof Char123LocaleChar125HowItWorksRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/private-label-sup': typeof Char123LocaleChar125PrivateLabelSupRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsRoute
  '/{-$locale}/solutions': typeof Char123LocaleChar125SolutionsRoute
  '/{-$locale}/sponsor': typeof Char123LocaleChar125SponsorRoute
  '/{-$locale}/sup-for-clubs': typeof Char123LocaleChar125SupForClubsRoute
  '/{-$locale}/sup-for-resorts': typeof Char123LocaleChar125SupForResortsRoute
  '/{-$locale}/sup-startup-brands': typeof Char123LocaleChar125SupStartupBrandsRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/waitlist': typeof Char123LocaleChar125WaitlistRoute
  '/{-$locale}/who-we-serve': typeof Char123LocaleChar125WhoWeServeRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatars/$': typeof ApiAvatarsSplatRoute
  '/api/inquiry-logo/$': typeof ApiInquiryLogoSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125authForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125authLoginRoute
  '/{-$locale}/register': typeof Char123LocaleChar125authRegisterRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125authResetPasswordRoute
  '/{-$locale}/verify-email': typeof Char123LocaleChar125authVerifyEmailRoute
  '/{-$locale}/admin/feedback': typeof Char123LocaleChar125AdminFeedbackRoute
  '/{-$locale}/admin/inquiries': typeof Char123LocaleChar125AdminInquiriesRoute
  '/{-$locale}/admin/sponsors': typeof Char123LocaleChar125AdminSponsorsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/{-$locale}/admin/waitlist': typeof Char123LocaleChar125AdminWaitlistRoute
  '/{-$locale}/app/account': typeof Char123LocaleChar125AppAccountRoute
  '/{-$locale}/app/feedback': typeof Char123LocaleChar125AppFeedbackRoute
  '/{-$locale}/app/pro': typeof Char123LocaleChar125AppProRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125AppIndexRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/inquiries.csv': typeof AdminInquiriesDotcsvRoute
  '/admin/sponsors.csv': typeof AdminSponsorsDotcsvRoute
  '/admin/waitlist.csv': typeof AdminWaitlistDotcsvRoute
  '/api/search': typeof ApiSearchRoute
  '/docs-md/$': typeof DocsMdSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125ChangelogRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/custom-sup-manufacturing': typeof Char123LocaleChar125CustomSupManufacturingRoute
  '/{-$locale}/customizer': typeof Char123LocaleChar125CustomizerRoute
  '/{-$locale}/gallery': typeof Char123LocaleChar125GalleryRoute
  '/{-$locale}/how-it-works': typeof Char123LocaleChar125HowItWorksRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/private-label-sup': typeof Char123LocaleChar125PrivateLabelSupRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsRoute
  '/{-$locale}/solutions': typeof Char123LocaleChar125SolutionsRoute
  '/{-$locale}/sponsor': typeof Char123LocaleChar125SponsorRoute
  '/{-$locale}/sup-for-clubs': typeof Char123LocaleChar125SupForClubsRoute
  '/{-$locale}/sup-for-resorts': typeof Char123LocaleChar125SupForResortsRoute
  '/{-$locale}/sup-startup-brands': typeof Char123LocaleChar125SupStartupBrandsRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/waitlist': typeof Char123LocaleChar125WaitlistRoute
  '/{-$locale}/who-we-serve': typeof Char123LocaleChar125WhoWeServeRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatars/$': typeof ApiAvatarsSplatRoute
  '/api/inquiry-logo/$': typeof ApiInquiryLogoSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125authForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125authLoginRoute
  '/{-$locale}/register': typeof Char123LocaleChar125authRegisterRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125authResetPasswordRoute
  '/{-$locale}/verify-email': typeof Char123LocaleChar125authVerifyEmailRoute
  '/{-$locale}/admin/feedback': typeof Char123LocaleChar125AdminFeedbackRoute
  '/{-$locale}/admin/inquiries': typeof Char123LocaleChar125AdminInquiriesRoute
  '/{-$locale}/admin/sponsors': typeof Char123LocaleChar125AdminSponsorsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/{-$locale}/admin/waitlist': typeof Char123LocaleChar125AdminWaitlistRoute
  '/{-$locale}/app/account': typeof Char123LocaleChar125AppAccountRoute
  '/{-$locale}/app/feedback': typeof Char123LocaleChar125AppFeedbackRoute
  '/{-$locale}/app/pro': typeof Char123LocaleChar125AppProRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/app': typeof Char123LocaleChar125AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRouteRouteWithChildren
  '/admin/inquiries.csv': typeof AdminInquiriesDotcsvRoute
  '/admin/sponsors.csv': typeof AdminSponsorsDotcsvRoute
  '/admin/waitlist.csv': typeof AdminWaitlistDotcsvRoute
  '/api/search': typeof ApiSearchRoute
  '/docs-md/$': typeof DocsMdSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125ChangelogRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/custom-sup-manufacturing': typeof Char123LocaleChar125CustomSupManufacturingRoute
  '/{-$locale}/customizer': typeof Char123LocaleChar125CustomizerRoute
  '/{-$locale}/gallery': typeof Char123LocaleChar125GalleryRoute
  '/{-$locale}/how-it-works': typeof Char123LocaleChar125HowItWorksRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/private-label-sup': typeof Char123LocaleChar125PrivateLabelSupRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsRoute
  '/{-$locale}/solutions': typeof Char123LocaleChar125SolutionsRoute
  '/{-$locale}/sponsor': typeof Char123LocaleChar125SponsorRoute
  '/{-$locale}/sup-for-clubs': typeof Char123LocaleChar125SupForClubsRoute
  '/{-$locale}/sup-for-resorts': typeof Char123LocaleChar125SupForResortsRoute
  '/{-$locale}/sup-startup-brands': typeof Char123LocaleChar125SupStartupBrandsRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/waitlist': typeof Char123LocaleChar125WaitlistRoute
  '/{-$locale}/who-we-serve': typeof Char123LocaleChar125WhoWeServeRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatars/$': typeof ApiAvatarsSplatRoute
  '/api/inquiry-logo/$': typeof ApiInquiryLogoSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/{-$locale}/(auth)/forgot-password': typeof Char123LocaleChar125authForgotPasswordRoute
  '/{-$locale}/(auth)/login': typeof Char123LocaleChar125authLoginRoute
  '/{-$locale}/(auth)/register': typeof Char123LocaleChar125authRegisterRoute
  '/{-$locale}/(auth)/reset-password': typeof Char123LocaleChar125authResetPasswordRoute
  '/{-$locale}/(auth)/verify-email': typeof Char123LocaleChar125authVerifyEmailRoute
  '/{-$locale}/admin/feedback': typeof Char123LocaleChar125AdminFeedbackRoute
  '/{-$locale}/admin/inquiries': typeof Char123LocaleChar125AdminInquiriesRoute
  '/{-$locale}/admin/sponsors': typeof Char123LocaleChar125AdminSponsorsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/{-$locale}/admin/waitlist': typeof Char123LocaleChar125AdminWaitlistRoute
  '/{-$locale}/app/account': typeof Char123LocaleChar125AppAccountRoute
  '/{-$locale}/app/feedback': typeof Char123LocaleChar125AppFeedbackRoute
  '/{-$locale}/app/pro': typeof Char123LocaleChar125AppProRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}/admin'
    | '/admin/inquiries.csv'
    | '/admin/sponsors.csv'
    | '/admin/waitlist.csv'
    | '/api/search'
    | '/docs-md/$'
    | '/docs/$'
    | '/{-$locale}/about'
    | '/{-$locale}/changelog'
    | '/{-$locale}/contact'
    | '/{-$locale}/custom-sup-manufacturing'
    | '/{-$locale}/customizer'
    | '/{-$locale}/gallery'
    | '/{-$locale}/how-it-works'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/private-label-sup'
    | '/{-$locale}/products'
    | '/{-$locale}/solutions'
    | '/{-$locale}/sponsor'
    | '/{-$locale}/sup-for-clubs'
    | '/{-$locale}/sup-for-resorts'
    | '/{-$locale}/sup-startup-brands'
    | '/{-$locale}/terms'
    | '/{-$locale}/waitlist'
    | '/{-$locale}/who-we-serve'
    | '/{-$locale}/'
    | '/api/auth/$'
    | '/api/avatars/$'
    | '/api/inquiry-logo/$'
    | '/api/webhooks/stripe'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/register'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/verify-email'
    | '/{-$locale}/admin/feedback'
    | '/{-$locale}/admin/inquiries'
    | '/{-$locale}/admin/sponsors'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/admin/waitlist'
    | '/{-$locale}/app/account'
    | '/{-$locale}/app/feedback'
    | '/{-$locale}/app/pro'
    | '/{-$locale}/admin/'
    | '/{-$locale}/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/inquiries.csv'
    | '/admin/sponsors.csv'
    | '/admin/waitlist.csv'
    | '/api/search'
    | '/docs-md/$'
    | '/docs/$'
    | '/{-$locale}/about'
    | '/{-$locale}/changelog'
    | '/{-$locale}/contact'
    | '/{-$locale}/custom-sup-manufacturing'
    | '/{-$locale}/customizer'
    | '/{-$locale}/gallery'
    | '/{-$locale}/how-it-works'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/private-label-sup'
    | '/{-$locale}/products'
    | '/{-$locale}/solutions'
    | '/{-$locale}/sponsor'
    | '/{-$locale}/sup-for-clubs'
    | '/{-$locale}/sup-for-resorts'
    | '/{-$locale}/sup-startup-brands'
    | '/{-$locale}/terms'
    | '/{-$locale}/waitlist'
    | '/{-$locale}/who-we-serve'
    | '/{-$locale}'
    | '/api/auth/$'
    | '/api/avatars/$'
    | '/api/inquiry-logo/$'
    | '/api/webhooks/stripe'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/register'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/verify-email'
    | '/{-$locale}/admin/feedback'
    | '/{-$locale}/admin/inquiries'
    | '/{-$locale}/admin/sponsors'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/admin/waitlist'
    | '/{-$locale}/app/account'
    | '/{-$locale}/app/feedback'
    | '/{-$locale}/app/pro'
    | '/{-$locale}/admin'
    | '/{-$locale}/app'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}/admin'
    | '/admin/inquiries.csv'
    | '/admin/sponsors.csv'
    | '/admin/waitlist.csv'
    | '/api/search'
    | '/docs-md/$'
    | '/docs/$'
    | '/{-$locale}/about'
    | '/{-$locale}/changelog'
    | '/{-$locale}/contact'
    | '/{-$locale}/custom-sup-manufacturing'
    | '/{-$locale}/customizer'
    | '/{-$locale}/gallery'
    | '/{-$locale}/how-it-works'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/private-label-sup'
    | '/{-$locale}/products'
    | '/{-$locale}/solutions'
    | '/{-$locale}/sponsor'
    | '/{-$locale}/sup-for-clubs'
    | '/{-$locale}/sup-for-resorts'
    | '/{-$locale}/sup-startup-brands'
    | '/{-$locale}/terms'
    | '/{-$locale}/waitlist'
    | '/{-$locale}/who-we-serve'
    | '/{-$locale}/'
    | '/api/auth/$'
    | '/api/avatars/$'
    | '/api/inquiry-logo/$'
    | '/api/webhooks/stripe'
    | '/{-$locale}/(auth)/forgot-password'
    | '/{-$locale}/(auth)/login'
    | '/{-$locale}/(auth)/register'
    | '/{-$locale}/(auth)/reset-password'
    | '/{-$locale}/(auth)/verify-email'
    | '/{-$locale}/admin/feedback'
    | '/{-$locale}/admin/inquiries'
    | '/{-$locale}/admin/sponsors'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/admin/waitlist'
    | '/{-$locale}/app/account'
    | '/{-$locale}/app/feedback'
    | '/{-$locale}/app/pro'
    | '/{-$locale}/admin/'
    | '/{-$locale}/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminInquiriesDotcsvRoute: typeof AdminInquiriesDotcsvRoute
  AdminSponsorsDotcsvRoute: typeof AdminSponsorsDotcsvRoute
  AdminWaitlistDotcsvRoute: typeof AdminWaitlistDotcsvRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsMdSplatRoute: typeof DocsMdSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAvatarsSplatRoute: typeof ApiAvatarsSplatRoute
  ApiInquiryLogoSplatRoute: typeof ApiInquiryLogoSplatRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/who-we-serve': {
      id: '/{-$locale}/who-we-serve'
      path: '/who-we-serve'
      fullPath: '/{-$locale}/who-we-serve'
      preLoaderRoute: typeof Char123LocaleChar125WhoWeServeRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/waitlist': {
      id: '/{-$locale}/waitlist'
      path: '/waitlist'
      fullPath: '/{-$locale}/waitlist'
      preLoaderRoute: typeof Char123LocaleChar125WaitlistRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/sup-startup-brands': {
      id: '/{-$locale}/sup-startup-brands'
      path: '/sup-startup-brands'
      fullPath: '/{-$locale}/sup-startup-brands'
      preLoaderRoute: typeof Char123LocaleChar125SupStartupBrandsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/sup-for-resorts': {
      id: '/{-$locale}/sup-for-resorts'
      path: '/sup-for-resorts'
      fullPath: '/{-$locale}/sup-for-resorts'
      preLoaderRoute: typeof Char123LocaleChar125SupForResortsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/sup-for-clubs': {
      id: '/{-$locale}/sup-for-clubs'
      path: '/sup-for-clubs'
      fullPath: '/{-$locale}/sup-for-clubs'
      preLoaderRoute: typeof Char123LocaleChar125SupForClubsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/sponsor': {
      id: '/{-$locale}/sponsor'
      path: '/sponsor'
      fullPath: '/{-$locale}/sponsor'
      preLoaderRoute: typeof Char123LocaleChar125SponsorRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/solutions': {
      id: '/{-$locale}/solutions'
      path: '/solutions'
      fullPath: '/{-$locale}/solutions'
      preLoaderRoute: typeof Char123LocaleChar125SolutionsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/products': {
      id: '/{-$locale}/products'
      path: '/products'
      fullPath: '/{-$locale}/products'
      preLoaderRoute: typeof Char123LocaleChar125ProductsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/private-label-sup': {
      id: '/{-$locale}/private-label-sup'
      path: '/private-label-sup'
      fullPath: '/{-$locale}/private-label-sup'
      preLoaderRoute: typeof Char123LocaleChar125PrivateLabelSupRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/pricing': {
      id: '/{-$locale}/pricing'
      path: '/pricing'
      fullPath: '/{-$locale}/pricing'
      preLoaderRoute: typeof Char123LocaleChar125PricingRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/how-it-works': {
      id: '/{-$locale}/how-it-works'
      path: '/how-it-works'
      fullPath: '/{-$locale}/how-it-works'
      preLoaderRoute: typeof Char123LocaleChar125HowItWorksRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/gallery': {
      id: '/{-$locale}/gallery'
      path: '/gallery'
      fullPath: '/{-$locale}/gallery'
      preLoaderRoute: typeof Char123LocaleChar125GalleryRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/customizer': {
      id: '/{-$locale}/customizer'
      path: '/customizer'
      fullPath: '/{-$locale}/customizer'
      preLoaderRoute: typeof Char123LocaleChar125CustomizerRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/custom-sup-manufacturing': {
      id: '/{-$locale}/custom-sup-manufacturing'
      path: '/custom-sup-manufacturing'
      fullPath: '/{-$locale}/custom-sup-manufacturing'
      preLoaderRoute: typeof Char123LocaleChar125CustomSupManufacturingRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/changelog': {
      id: '/{-$locale}/changelog'
      path: '/changelog'
      fullPath: '/{-$locale}/changelog'
      preLoaderRoute: typeof Char123LocaleChar125ChangelogRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-md/$': {
      id: '/docs-md/$'
      path: '/docs-md/$'
      fullPath: '/docs-md/$'
      preLoaderRoute: typeof DocsMdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlist.csv': {
      id: '/admin/waitlist.csv'
      path: '/admin/waitlist.csv'
      fullPath: '/admin/waitlist.csv'
      preLoaderRoute: typeof AdminWaitlistDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors.csv': {
      id: '/admin/sponsors.csv'
      path: '/admin/sponsors.csv'
      fullPath: '/admin/sponsors.csv'
      preLoaderRoute: typeof AdminSponsorsDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries.csv': {
      id: '/admin/inquiries.csv'
      path: '/admin/inquiries.csv'
      fullPath: '/admin/inquiries.csv'
      preLoaderRoute: typeof AdminInquiriesDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/admin': {
      id: '/{-$locale}/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125AdminRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/app/': {
      id: '/{-$locale}/app/'
      path: '/app'
      fullPath: '/{-$locale}/app/'
      preLoaderRoute: typeof Char123LocaleChar125AppIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/admin/': {
      id: '/{-$locale}/admin/'
      path: '/'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125AdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/app/pro': {
      id: '/{-$locale}/app/pro'
      path: '/app/pro'
      fullPath: '/{-$locale}/app/pro'
      preLoaderRoute: typeof Char123LocaleChar125AppProRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/app/feedback': {
      id: '/{-$locale}/app/feedback'
      path: '/app/feedback'
      fullPath: '/{-$locale}/app/feedback'
      preLoaderRoute: typeof Char123LocaleChar125AppFeedbackRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/app/account': {
      id: '/{-$locale}/app/account'
      path: '/app/account'
      fullPath: '/{-$locale}/app/account'
      preLoaderRoute: typeof Char123LocaleChar125AppAccountRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/admin/waitlist': {
      id: '/{-$locale}/admin/waitlist'
      path: '/waitlist'
      fullPath: '/{-$locale}/admin/waitlist'
      preLoaderRoute: typeof Char123LocaleChar125AdminWaitlistRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/admin/users': {
      id: '/{-$locale}/admin/users'
      path: '/users'
      fullPath: '/{-$locale}/admin/users'
      preLoaderRoute: typeof Char123LocaleChar125AdminUsersRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/admin/sponsors': {
      id: '/{-$locale}/admin/sponsors'
      path: '/sponsors'
      fullPath: '/{-$locale}/admin/sponsors'
      preLoaderRoute: typeof Char123LocaleChar125AdminSponsorsRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/admin/inquiries': {
      id: '/{-$locale}/admin/inquiries'
      path: '/inquiries'
      fullPath: '/{-$locale}/admin/inquiries'
      preLoaderRoute: typeof Char123LocaleChar125AdminInquiriesRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/admin/feedback': {
      id: '/{-$locale}/admin/feedback'
      path: '/feedback'
      fullPath: '/{-$locale}/admin/feedback'
      preLoaderRoute: typeof Char123LocaleChar125AdminFeedbackRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/(auth)/verify-email': {
      id: '/{-$locale}/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/{-$locale}/verify-email'
      preLoaderRoute: typeof Char123LocaleChar125authVerifyEmailRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)/reset-password': {
      id: '/{-$locale}/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/{-$locale}/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125authResetPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)/register': {
      id: '/{-$locale}/(auth)/register'
      path: '/register'
      fullPath: '/{-$locale}/register'
      preLoaderRoute: typeof Char123LocaleChar125authRegisterRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)/login': {
      id: '/{-$locale}/(auth)/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125authLoginRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)/forgot-password': {
      id: '/{-$locale}/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/{-$locale}/forgot-password'
      preLoaderRoute: typeof Char123LocaleChar125authForgotPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquiry-logo/$': {
      id: '/api/inquiry-logo/$'
      path: '/api/inquiry-logo/$'
      fullPath: '/api/inquiry-logo/$'
      preLoaderRoute: typeof ApiInquiryLogoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatars/$': {
      id: '/api/avatars/$'
      path: '/api/avatars/$'
      fullPath: '/api/avatars/$'
      preLoaderRoute: typeof ApiAvatarsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125AdminRouteRouteChildren {
  Char123LocaleChar125AdminFeedbackRoute: typeof Char123LocaleChar125AdminFeedbackRoute
  Char123LocaleChar125AdminInquiriesRoute: typeof Char123LocaleChar125AdminInquiriesRoute
  Char123LocaleChar125AdminSponsorsRoute: typeof Char123LocaleChar125AdminSponsorsRoute
  Char123LocaleChar125AdminUsersRoute: typeof Char123LocaleChar125AdminUsersRoute
  Char123LocaleChar125AdminWaitlistRoute: typeof Char123LocaleChar125AdminWaitlistRoute
  Char123LocaleChar125AdminIndexRoute: typeof Char123LocaleChar125AdminIndexRoute
}

const Char123LocaleChar125AdminRouteRouteChildren: Char123LocaleChar125AdminRouteRouteChildren =
  {
    Char123LocaleChar125AdminFeedbackRoute:
      Char123LocaleChar125AdminFeedbackRoute,
    Char123LocaleChar125AdminInquiriesRoute:
      Char123LocaleChar125AdminInquiriesRoute,
    Char123LocaleChar125AdminSponsorsRoute:
      Char123LocaleChar125AdminSponsorsRoute,
    Char123LocaleChar125AdminUsersRoute: Char123LocaleChar125AdminUsersRoute,
    Char123LocaleChar125AdminWaitlistRoute:
      Char123LocaleChar125AdminWaitlistRoute,
    Char123LocaleChar125AdminIndexRoute: Char123LocaleChar125AdminIndexRoute,
  }

const Char123LocaleChar125AdminRouteRouteWithChildren =
  Char123LocaleChar125AdminRouteRoute._addFileChildren(
    Char123LocaleChar125AdminRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AdminRouteRoute: typeof Char123LocaleChar125AdminRouteRouteWithChildren
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ChangelogRoute: typeof Char123LocaleChar125ChangelogRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125CustomSupManufacturingRoute: typeof Char123LocaleChar125CustomSupManufacturingRoute
  Char123LocaleChar125CustomizerRoute: typeof Char123LocaleChar125CustomizerRoute
  Char123LocaleChar125GalleryRoute: typeof Char123LocaleChar125GalleryRoute
  Char123LocaleChar125HowItWorksRoute: typeof Char123LocaleChar125HowItWorksRoute
  Char123LocaleChar125PricingRoute: typeof Char123LocaleChar125PricingRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125PrivateLabelSupRoute: typeof Char123LocaleChar125PrivateLabelSupRoute
  Char123LocaleChar125ProductsRoute: typeof Char123LocaleChar125ProductsRoute
  Char123LocaleChar125SolutionsRoute: typeof Char123LocaleChar125SolutionsRoute
  Char123LocaleChar125SponsorRoute: typeof Char123LocaleChar125SponsorRoute
  Char123LocaleChar125SupForClubsRoute: typeof Char123LocaleChar125SupForClubsRoute
  Char123LocaleChar125SupForResortsRoute: typeof Char123LocaleChar125SupForResortsRoute
  Char123LocaleChar125SupStartupBrandsRoute: typeof Char123LocaleChar125SupStartupBrandsRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125WaitlistRoute: typeof Char123LocaleChar125WaitlistRoute
  Char123LocaleChar125WhoWeServeRoute: typeof Char123LocaleChar125WhoWeServeRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125authForgotPasswordRoute: typeof Char123LocaleChar125authForgotPasswordRoute
  Char123LocaleChar125authLoginRoute: typeof Char123LocaleChar125authLoginRoute
  Char123LocaleChar125authRegisterRoute: typeof Char123LocaleChar125authRegisterRoute
  Char123LocaleChar125authResetPasswordRoute: typeof Char123LocaleChar125authResetPasswordRoute
  Char123LocaleChar125authVerifyEmailRoute: typeof Char123LocaleChar125authVerifyEmailRoute
  Char123LocaleChar125AppAccountRoute: typeof Char123LocaleChar125AppAccountRoute
  Char123LocaleChar125AppFeedbackRoute: typeof Char123LocaleChar125AppFeedbackRoute
  Char123LocaleChar125AppProRoute: typeof Char123LocaleChar125AppProRoute
  Char123LocaleChar125AppIndexRoute: typeof Char123LocaleChar125AppIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AdminRouteRoute:
      Char123LocaleChar125AdminRouteRouteWithChildren,
    Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
    Char123LocaleChar125ChangelogRoute: Char123LocaleChar125ChangelogRoute,
    Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
    Char123LocaleChar125CustomSupManufacturingRoute:
      Char123LocaleChar125CustomSupManufacturingRoute,
    Char123LocaleChar125CustomizerRoute: Char123LocaleChar125CustomizerRoute,
    Char123LocaleChar125GalleryRoute: Char123LocaleChar125GalleryRoute,
    Char123LocaleChar125HowItWorksRoute: Char123LocaleChar125HowItWorksRoute,
    Char123LocaleChar125PricingRoute: Char123LocaleChar125PricingRoute,
    Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
    Char123LocaleChar125PrivateLabelSupRoute:
      Char123LocaleChar125PrivateLabelSupRoute,
    Char123LocaleChar125ProductsRoute: Char123LocaleChar125ProductsRoute,
    Char123LocaleChar125SolutionsRoute: Char123LocaleChar125SolutionsRoute,
    Char123LocaleChar125SponsorRoute: Char123LocaleChar125SponsorRoute,
    Char123LocaleChar125SupForClubsRoute: Char123LocaleChar125SupForClubsRoute,
    Char123LocaleChar125SupForResortsRoute:
      Char123LocaleChar125SupForResortsRoute,
    Char123LocaleChar125SupStartupBrandsRoute:
      Char123LocaleChar125SupStartupBrandsRoute,
    Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
    Char123LocaleChar125WaitlistRoute: Char123LocaleChar125WaitlistRoute,
    Char123LocaleChar125WhoWeServeRoute: Char123LocaleChar125WhoWeServeRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125authForgotPasswordRoute:
      Char123LocaleChar125authForgotPasswordRoute,
    Char123LocaleChar125authLoginRoute: Char123LocaleChar125authLoginRoute,
    Char123LocaleChar125authRegisterRoute:
      Char123LocaleChar125authRegisterRoute,
    Char123LocaleChar125authResetPasswordRoute:
      Char123LocaleChar125authResetPasswordRoute,
    Char123LocaleChar125authVerifyEmailRoute:
      Char123LocaleChar125authVerifyEmailRoute,
    Char123LocaleChar125AppAccountRoute: Char123LocaleChar125AppAccountRoute,
    Char123LocaleChar125AppFeedbackRoute: Char123LocaleChar125AppFeedbackRoute,
    Char123LocaleChar125AppProRoute: Char123LocaleChar125AppProRoute,
    Char123LocaleChar125AppIndexRoute: Char123LocaleChar125AppIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminInquiriesDotcsvRoute: AdminInquiriesDotcsvRoute,
  AdminSponsorsDotcsvRoute: AdminSponsorsDotcsvRoute,
  AdminWaitlistDotcsvRoute: AdminWaitlistDotcsvRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsMdSplatRoute: DocsMdSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAvatarsSplatRoute: ApiAvatarsSplatRoute,
  ApiInquiryLogoSplatRoute: ApiInquiryLogoSplatRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
