/**
 * Product-specific edge redirect rules.
 *
 * These 301 redirects handle legacy URL migration from previous site
 * versions. When deploying a new product, replace these with the new
 * site's redirect policy. The gatePath() logic in edge-gate.ts is
 * framework-level and consumes this map.
 */

import { GONE_PATHS, ABOUT_BRAND_PATH } from '@/config/navigation'
import { BRAND_PARENT_URL } from '@/config/branding'

export const EDGE_REDIRECTS: Record<string, string> = {
  '/oem-odm': '/oem-manufacturing',
  '/zh/oem-odm': '/es/oem-manufacturing',
  '/oem-odm-manufacturer': '/oem-manufacturing',
  '/es/oem-odm-manufacturer': '/es/oem-manufacturing',
  '/zh/oem-odm-manufacturer': '/es/oem-manufacturing',
  '/news/afarer-supply-chain-2025': '/news',
  '/news/seeking-dealers-for-afarer': '/news',
  '/request-quotation': '/contact',
  '/es/request-quotation': '/es/contact',
  '/fabricant-sup-gonflable': '/oem-manufacturing',
  '/bateau-gonflable-fabricant': '/oem-manufacturing',
  '/fournisseur-nautique': '/solutions/rental-operators',
  '/custom': '/product-development',
  '/es/custom': '/es/product-development',
  '/quality-testing': '/quality',
  '/es/quality-testing': '/es/quality',
  '/safety': '/quality',
  '/es/safety': '/es/quality',
  '/trust': '/quality',
  '/es/trust': '/es/quality',
  '/quality-control': '/factory/quality-inspection',
  '/es/quality-control': '/es/factory/quality-inspection',
  '/solutions/resorts-hotels': '/solutions/resort-sup',
  '/es/solutions/resorts-hotels': '/es/solutions/resort-sup',
  '/solutions/paddle-clubs': '/solutions/club-sup',
  '/es/solutions/paddle-clubs': '/es/solutions/club-sup',
  '/solutions/build-your-own-brand': '/solutions/private-label-sup',
  '/es/solutions/build-your-own-brand': '/es/solutions/private-label-sup',
  '/afarer': ABOUT_BRAND_PATH,
  '/es/afarer': '/es/about/afarer',
  '/zh/afarer': '/es/about/afarer',
  '/brand': '/about',
  '/es/brand': '/es/about',
  '/zh/brand': '/es/about',
  '/brand/afarer': ABOUT_BRAND_PATH,
  '/es/brand/afarer': '/es/about/afarer',
  '/zh/brand/afarer': '/es/about/afarer',
  '/brand/story': ABOUT_BRAND_PATH,
  '/es/brand/story': '/es/about/afarer',
  '/zh/brand/story': '/es/about/afarer',
  '/brand/global-presence': '/about',
  '/es/brand/global-presence': '/es/about',
  '/brand/marine-expertise': '/about',
  '/es/brand/marine-expertise': '/es/about',
  '/brand/team': '/about',
  '/es/brand/team': '/es/about',
  '/brand/why-afarer': ABOUT_BRAND_PATH,
  '/es/brand/why-afarer': '/es/about/afarer',
  '/commercial-workboats': `${BRAND_PARENT_URL}/commercial-workboats`,
  '/es/commercial-workboats': `${BRAND_PARENT_URL}/es/commercial-workboats`,
  '/zh/commercial-workboats': `${BRAND_PARENT_URL}/es/commercial-workboats`,
  '/maritime-safety-defense': `${BRAND_PARENT_URL}/maritime-safety-defense`,
  '/es/maritime-safety-defense': `${BRAND_PARENT_URL}/es/maritime-safety-defense`,
  '/zh/maritime-safety-defense': `${BRAND_PARENT_URL}/es/maritime-safety-defense`,
  '/search-and-rescue': `${BRAND_PARENT_URL}/search-and-rescue`,
  '/es/search-and-rescue': `${BRAND_PARENT_URL}/es/search-and-rescue`,
  '/zh/search-and-rescue': `${BRAND_PARENT_URL}/es/search-and-rescue`,
  '/disaster-relief-humanitarian-aid': `${BRAND_PARENT_URL}/disaster-relief-humanitarian-aid`,
  '/es/disaster-relief-humanitarian-aid': `${BRAND_PARENT_URL}/es/disaster-relief-humanitarian-aid`,
  '/zh/disaster-relief-humanitarian-aid': `${BRAND_PARENT_URL}/es/disaster-relief-humanitarian-aid`,
  '/products/life-vest-classic': `${BRAND_PARENT_URL}/products/life-vest-classic`,
  '/es/products/life-vest-classic': `${BRAND_PARENT_URL}/es/products/life-vest-classic`,
  '/zh/products/life-vest-classic': `${BRAND_PARENT_URL}/es/products/life-vest-classic`,
  '/products/life-vest-pro': `${BRAND_PARENT_URL}/products/life-vest-pro`,
  '/es/products/life-vest-pro': `${BRAND_PARENT_URL}/es/products/life-vest-pro`,
  '/zh/products/life-vest-pro': `${BRAND_PARENT_URL}/es/products/life-vest-pro`,
  '/products/oars-pump-set': `${BRAND_PARENT_URL}/products/oars-pump-set`,
  '/es/products/oars-pump-set': `${BRAND_PARENT_URL}/es/products/oars-pump-set`,
  '/zh/products/oars-pump-set': `${BRAND_PARENT_URL}/es/products/oars-pump-set`,
  '/learn': '/knowledge',
  '/es/learn': '/es/knowledge',
  '/academy': '/knowledge',
  '/es/academy': '/es/knowledge',
  '/guides': '/knowledge',
  '/es/guides': '/es/knowledge',
  '/research': '/knowledge',
  '/es/research': '/es/knowledge',
  '/resources': '/knowledge',
  '/es/resources': '/es/knowledge',
  '/es/resources/download-catalog': '/es/products',
  '/community': '/knowledge',
  '/es/community': '/es/knowledge',
  '/lifestyle': '/knowledge',
  '/es/lifestyle': '/es/knowledge',
  '/journal': '/news',
  '/es/journal': '/es/news',
  '/media': '/products',
  '/es/media': '/es/products',
  '/evidence': '/projects',
  '/es/evidence': '/es/projects',
  '/case-studies': '/projects',
  '/es/case-studies': '/es/projects',
  '/whitepaper/oem-sup-manufacturing-guide': '/oem-manufacturing',
  '/es/whitepaper/oem-sup-manufacturing-guide': '/es/oem-manufacturing',
  '/news/sup-oem-shipping-logistics': '/news/private-label-sup-oem-guide',
  '/es/news/sup-oem-shipping-logistics': '/es/news/private-label-sup-oem-guide',
  '/news/importing-sup-from-china-guide': '/news/private-label-sup-guide',
  '/es/news/importing-sup-from-china-guide': '/es/news/private-label-sup-guide',
}

export { GONE_PATHS }
