import type { Localized } from './content'
import { getFacts } from './facts'

const fEn = getFacts('en')
const fEs = getFacts('es')
const fFr = getFacts('fr')
const fDe = getFacts('de')
const fIt = getFacts('it')

/**
 * B2B procurement profiles for the series platform pages (/products/{series}).
 *
 * Backed by the category engineering & sourcing matrix (Qingdao Vatrad Group,
 * SPEC-CAT-2026-V1): dimensions, construction, capacity/PSI and buyer fit per
 * platform. MOQ / lead-time figures stay aligned with FACTS (single source of
 * truth); commercial wording follows the site's RFQ triage guidance.
 */

export interface ProcurementRow {
  label: string
  value: string
}

export interface ProcurementProfile {
  bestFor: string
  sizes: string
  construction: string
  customization: string
  moq: string
  leadTime: string
  specRows: ProcurementRow[]
  keyQuestions: string[]
}

export const procurementProfiles: Localized<Record<string, ProcurementProfile>> = {
  en: {
    'all-around': {
      bestFor: 'Entry-level retail, resorts & rental programs',
      sizes: "10'0\"–11'6\" · 31\"–34\" wide · 120/150 mm",
      construction: 'Single-layer fusion or MSL double-layer drop-stitch',
      customization: 'Graphics, EVA, accessories & retail packaging',
      moq: `From ${fEn.moq.standardRun} pcs per project — trial runs from ${fEn.moq.trialStandard}`,
      leadTime: `Samples in ${fEn.sampleTime} · production in ${fEn.leadTime} after confirmed PO and deposit`,
      specRows: [
        { label: 'Use scenario', value: 'Entry-level retail lines, resort & rental programs, DTC e-commerce' },
        { label: 'Available sizes', value: "10'0\"–11'6\" × 31\"–34\" × 120/150 mm" },
        { label: 'Construction', value: 'Single-layer fusion / MSL double-layer drop-stitch' },
        { label: 'Rider weight', value: '60–110 kg optimal' },
        { label: 'Max payload', value: '140 kg' },
        { label: 'Recommended / max pressure', value: '15.0 / 18.0 PSI' },
        { label: 'Fin system', value: 'US box / slide-in options' },
        { label: 'Standard package', value: 'Pump, paddle, backpack, fin, leash, repair kit' },
      ],
      keyQuestions: [
        'Target retail level and rider profile',
        'Single-user or family/duo use',
        'Standard or full accessory kit',
      ],
    },
    race: {
      bestFor: 'Racing clubs, training academies & performance brands',
      sizes: "12'6\"–14'0\" · 24\"–27\" wide · 150 mm",
      construction: 'Ultra-stiff linear woven drop-stitch + carbon stringer',
      customization: 'Race layup, width, fin system & club graphics',
      moq: `From ${fEn.moq.standardRun} pcs per project — trial runs from ${fEn.moq.trialStandard}`,
      leadTime: `Samples in ${fEn.sampleTime} · production in ${fEn.leadTime} after confirmed PO and deposit`,
      specRows: [
        { label: 'Use scenario', value: 'Racing clubs, athletic training academies, performance brands' },
        { label: 'Available sizes', value: "12'6\"–14'0\" × 24\"–27\" × 150 mm" },
        { label: 'Construction', value: 'Ultra-stiff linear woven + carbon stringer reinforcement' },
        { label: 'Rider weight', value: '65–95 kg optimal' },
        { label: 'Max payload', value: '120 kg' },
        { label: 'Recommended / max pressure', value: '18.0 / 22.0 PSI' },
        { label: 'Fin system', value: 'Race fin / US box / click-fin options' },
        { label: 'Standard package', value: 'Pump, race paddle, backpack, fin, repair kit' },
      ],
      keyQuestions: [
        "12'6\" or 14' platform",
        'Target width and board weight',
        'Fin system and racing class',
        'Club, competition or retail use',
      ],
    },
    surf: {
      bestFor: 'Surf brands, surf schools & hybrid product lines',
      sizes: "8'6\"–10'6\" · 30\"–34\" wide",
      construction: 'Wave-specific shaping, reinforced rails & raised rocker',
      customization: 'Rocker, rails, deck graphics & soft-top options',
      moq: `From ${fEn.moq.standardRun} pcs per project — trial runs from ${fEn.moq.trialStandard}`,
      leadTime: `Samples in ${fEn.sampleTime} · production in ${fEn.leadTime} after confirmed PO and deposit`,
      specRows: [
        { label: 'Use scenario', value: 'Wave riding, surf schools, hybrid retail lines' },
        { label: 'Available sizes', value: "8'6\"–10'6\" × 30\"–34\" wide" },
        { label: 'Construction', value: 'Wave-specific shaping with reinforced rails' },
        { label: 'Fin system', value: 'US box / fixed fin options' },
        { label: 'Standard package', value: 'Pump, paddle, backpack, fin, repair kit' },
      ],
      keyQuestions: [
        'Target rider weight and wave type',
        'Soft-top style or performance layup',
        'Mixed fleet with other platforms',
      ],
    },
    touring: {
      bestFor: 'Expedition brands, touring fleets & premium retail lines',
      sizes: "11'6\"–12'6\" · 30\"–32\" wide · 150 mm",
      construction: 'Woven drop-stitch + reinforced double rail tape',
      customization: 'Cargo bungees, mounting points, graphics & accessories',
      moq: `From ${fEn.moq.standardRun} pcs per project — trial runs from ${fEn.moq.trialStandard}`,
      leadTime: `Samples in ${fEn.sampleTime} · production in ${fEn.leadTime} after confirmed PO and deposit`,
      specRows: [
        { label: 'Use scenario', value: 'Long-distance touring, expedition programs, premium retail' },
        { label: 'Available sizes', value: "11'6\"–12'6\" × 30\"–32\" × 150 mm" },
        { label: 'Construction', value: 'Woven drop-stitch + reinforced double rail tape' },
        { label: 'Rider weight', value: '75–130 kg optimal' },
        { label: 'Max payload', value: '160 kg' },
        { label: 'Recommended / max pressure', value: '15.0 / 20.0 PSI' },
        { label: 'Fin system', value: 'US box / slide-in options' },
        { label: 'Standard package', value: 'Pump, paddle, backpack, fin, leash, repair kit' },
      ],
      keyQuestions: [
        'Volume and cargo capacity needs',
        'Front/rear bungee and mounting points',
        'Long-distance cruise positioning and target board length',
      ],
    },
    yoga: {
      bestFor: 'Water fitness studios, resort wellness & SUP yoga fleets',
      sizes: "10'8\"–11'0\" · 34\"–36\" wide · 150 mm",
      construction: 'Wide stable platform + full-deck embossed EVA traction',
      customization: 'EVA coverage, artwork, anchors & accessory kit',
      moq: `From ${fEn.moq.standardRun} pcs per project — trial runs from ${fEn.moq.trialStandard}`,
      leadTime: `Samples in ${fEn.sampleTime} · production in ${fEn.leadTime} after confirmed PO and deposit`,
      specRows: [
        { label: 'Use scenario', value: 'Water fitness studios, resort wellness retreats, SUP yoga fleets' },
        { label: 'Available sizes', value: "10'8\"–11'0\" × 34\"–36\" × 150 mm" },
        { label: 'Construction', value: 'Wide stable platform + full-deck embossed EVA traction' },
        { label: 'Rider weight', value: '50–120 kg optimal' },
        { label: 'Max payload', value: '150 kg' },
        { label: 'Recommended / max pressure', value: '15.0 / 18.0 PSI' },
        { label: 'Standard package', value: 'Pump, paddle, backpack, fin, repair kit' },
      ],
      keyQuestions: [
        'EVA coverage and anchor points',
        'Group class quantity',
        'Commercial use frequency',
      ],
    },
    whitewater: {
      bestFor: 'Lifestyle & designer brands, boutique retail',
      sizes: "10'6\"–11'6\" · 32\"–34\" wide",
      construction: 'Project-specific drop-stitch & PVC with embossing options',
      customization: 'Full-board art, embossing, EVA piecing & coordinated accessories',
      moq: `From ${fEn.moq.standardRun} pcs per project — trial runs from ${fEn.moq.trialStandard}`,
      leadTime: `Samples in ${fEn.sampleTime} · production in ${fEn.leadTime} after confirmed PO and deposit`,
      specRows: [
        { label: 'Use scenario', value: 'Designer editions, lifestyle retail, boutique travel programs' },
        { label: 'Available sizes', value: "10'6\"–11'6\" × 32\"–34\" wide" },
        { label: 'Construction', value: 'Project-specific drop-stitch & PVC, mechanical embossing options' },
        { label: 'Fin system', value: 'US box / slide-in options' },
        { label: 'Standard package', value: 'Pump, paddle, backpack, fin, repair kit' },
      ],
      keyQuestions: [
        'Artwork complexity and printing method',
        'Coordinated accessory kit',
        'Retail packaging style',
      ],
    },
    fishing: {
      bestFor: 'Angling brands, fishing outfitters & sporting shops',
      sizes: "11'6\"–12'0\" · 34\"–38\" wide · 150 mm",
      construction: 'Heavy-duty dual-layer + multiple D-rings & accessory mounts',
      customization: 'Seat, cooler and rod-holder integration, D-ring layouts',
      moq: `From ${fEn.moq.standardRun} pcs per project — trial runs from ${fEn.moq.trialStandard}`,
      leadTime: `Samples in ${fEn.sampleTime} · production in ${fEn.leadTime} after confirmed PO and deposit`,
      specRows: [
        { label: 'Use scenario', value: 'Angling equipment brands, fishing outfitters, outdoor sporting shops' },
        { label: 'Available sizes', value: "11'6\"–12'0\" × 34\"–38\" × 150 mm" },
        { label: 'Construction', value: 'Heavy-duty dual-layer + multiple D-rings & accessory mounts' },
        { label: 'Rider weight', value: '80–150 kg optimal' },
        { label: 'Max payload', value: '200 kg' },
        { label: 'Recommended / max pressure', value: '15.0 / 18.0 PSI' },
        { label: 'Standard package', value: 'Pump, paddle, backpack, fin, repair kit' },
      ],
      keyQuestions: [
        'Seat, cooler and rod-holder integration',
        'D-ring / rail layout and payload needs',
        'Standing stability target',
      ],
    },
    kids: {
      bestFor: 'Youth paddling clubs, schools & family retail brands',
      sizes: "8'0\"–9'6\" · 26\"–28\" wide · 100/120 mm",
      construction: 'Lightweight drop-stitch + high-visibility safety graphics',
      customization: 'Age-specific sizing, visibility colorways & paddle length',
      moq: `From ${fEn.moq.standardRun} pcs per project — trial runs from ${fEn.moq.trialStandard}`,
      leadTime: `Samples in ${fEn.sampleTime} · production in ${fEn.leadTime} after confirmed PO and deposit`,
      specRows: [
        { label: 'Use scenario', value: 'Youth paddling clubs, school physical training, family retail' },
        { label: 'Available sizes', value: "8'0\"–9'6\" × 26\"–28\" × 100/120 mm" },
        { label: 'Construction', value: 'Lightweight drop-stitch + high-visibility safety graphics' },
        { label: 'Rider weight', value: '30–65 kg optimal' },
        { label: 'Max payload', value: '80 kg' },
        { label: 'Recommended / max pressure', value: '12.0 / 15.0 PSI' },
        { label: 'Standard package', value: 'Pump, kids paddle, backpack, fin, repair kit' },
      ],
      keyQuestions: [
        'Age range and board weight target',
        'Visibility colorway and matching paddle length',
        'School or club program volume',
      ],
    },
    multi: {
      bestFor: 'Team-building organizers, water parks & commercial tour operators',
      sizes: "15'0\"–18'0\" · 50\"–60\" wide · 200 mm",
      construction: 'Heavy-duty multi-chamber woven drop-stitch, dual valves',
      customization: 'Fleet numbering, logo placement, handles & D-ring layouts',
      moq: `From ${fEn.moq.standardRun} pcs per project — trial runs from ${fEn.moq.trialStandard}`,
      leadTime: `Samples in ${fEn.sampleTime} · production in ${fEn.leadTime} after confirmed PO and deposit`,
      specRows: [
        { label: 'Use scenario', value: 'Team-building organizers, water parks, commercial tour operators' },
        { label: 'Available sizes', value: "15'0\"–18'0\" × 50\"–60\" × 200 mm" },
        { label: 'Construction', value: 'Heavy-duty multi-chamber woven drop-stitch, dual valves' },
        { label: 'Crew size', value: '4–8 riders' },
        { label: 'Max payload', value: '650 kg' },
        { label: 'Recommended / max pressure', value: '15.0 / 18.0 PSI' },
        { label: 'Standard package', value: 'Pump(s), paddles, backpack(s), repair kit' },
      ],
      keyQuestions: [
        'Number of riders and total payload',
        'Operational scenario and storage conditions',
        'Fleet numbering and branding',
      ],
    },
  },
  es: {
    'all-around': {
      bestFor: 'Retail de entrada, resorts y programas de alquiler',
      sizes: "10'0\"–11'6\" · 31\"–34\" ancho · 120/150 mm",
      construction: 'Drop-stitch de capa única fusionada o MSL doble capa',
      customization: 'Gráficos, EVA, accesorios y embalaje minorista',
      moq: `Desde ${fEs.moq.standardRun} uds. por proyecto — pedidos de prueba desde ${fEs.moq.trialStandard}`,
      leadTime: `Muestras en ${fEs.sampleTime} · producción en ${fEs.leadTime} tras confirmar PO y depósito`,
      specRows: [
        { label: 'Escenario de uso', value: 'Líneas retail de entrada, programas de resort y alquiler, e-commerce DTC' },
        { label: 'Tamaños disponibles', value: "10'0\"–11'6\" × 31\"–34\" × 120/150 mm" },
        { label: 'Construcción', value: 'Drop-stitch de capa única fusionada / MSL doble capa' },
        { label: 'Peso del rider', value: '60–110 kg óptimo' },
        { label: 'Carga máxima', value: '140 kg' },
        { label: 'Presión recomendada / máxima', value: '15,0 / 18,0 PSI' },
        { label: 'Sistema de aletas', value: 'Caja US / opciones deslizantes' },
        { label: 'Paquete estándar', value: 'Bomba, pala, mochila, aleta, leash, kit de reparación' },
      ],
      keyQuestions: [
        'Nivel retail objetivo y perfil del rider',
        'Uso individual o familiar/de dos',
        'Kit de accesorios estándar o completo',
      ],
    },
    race: {
      bestFor: 'Clubes de competición, academias de entrenamiento y marcas de rendimiento',
      sizes: "12'6\"–14'0\" · 24\"–27\" ancho · 150 mm",
      construction: 'Drop-stitch woven lineal ultra rígido + refuerzo de carbono',
      customization: 'Layup de competición, ancho, sistema de aletas y gráficos de club',
      moq: `Desde ${fEs.moq.standardRun} uds. por proyecto — pedidos de prueba desde ${fEs.moq.trialStandard}`,
      leadTime: `Muestras en ${fEs.sampleTime} · producción en ${fEs.leadTime} tras confirmar PO y depósito`,
      specRows: [
        { label: 'Escenario de uso', value: 'Clubes de competición, academias de entrenamiento, marcas de rendimiento' },
        { label: 'Tamaños disponibles', value: "12'6\"–14'0\" × 24\"–27\" × 150 mm" },
        { label: 'Construcción', value: 'Woven lineal ultra rígido + refuerzo de stringer de carbono' },
        { label: 'Peso del rider', value: '65–95 kg óptimo' },
        { label: 'Carga máxima', value: '120 kg' },
        { label: 'Presión recomendada / máxima', value: '18,0 / 22,0 PSI' },
        { label: 'Sistema de aletas', value: 'Aleta de competición / caja US / click-fin' },
        { label: 'Paquete estándar', value: 'Bomba, pala de competición, mochila, aleta, kit de reparación' },
      ],
      keyQuestions: [
        'Plataforma 12′6″ o 14′',
        'Ancho y peso de tabla objetivo',
        'Sistema de aletas y clase de competición',
        'Uso en club, competición o retail',
      ],
    },
    surf: {
      bestFor: 'Marcas de surf, escuelas de surf y líneas híbridas',
      sizes: "8'6\"–10'6\" · 30\"–34\" ancho",
      construction: 'Formas específicas de ola, rails reforzados y rocker elevado',
      customization: 'Rocker, rails, gráficos de cubierta y opciones soft-top',
      moq: `Desde ${fEs.moq.standardRun} uds. por proyecto — pedidos de prueba desde ${fEs.moq.trialStandard}`,
      leadTime: `Muestras en ${fEs.sampleTime} · producción en ${fEs.leadTime} tras confirmar PO y depósito`,
      specRows: [
        { label: 'Escenario de uso', value: 'Surf de olas, escuelas de surf, líneas retail híbridas' },
        { label: 'Tamaños disponibles', value: "8'6\"–10'6\" × 30\"–34\" ancho" },
        { label: 'Construcción', value: 'Formas específicas de ola con rails reforzados' },
        { label: 'Sistema de aletas', value: 'Caja US / opciones de aleta fija' },
        { label: 'Paquete estándar', value: 'Bomba, pala, mochila, aleta, kit de reparación' },
      ],
      keyQuestions: [
        'Peso del rider objetivo y tipo de ola',
        'Estilo soft-top o layup de rendimiento',
        'Flota mixta con otras plataformas',
      ],
    },
    touring: {
      bestFor: 'Marcas de expedición, flotas de travesía y líneas retail premium',
      sizes: "11'6\"–12'6\" · 30\"–32\" ancho · 150 mm",
      construction: 'Drop-stitch woven + cinta de rail doble reforzada',
      customization: 'Bungees de carga, puntos de montaje, gráficos y accesorios',
      moq: `Desde ${fEs.moq.standardRun} uds. por proyecto — pedidos de prueba desde ${fEs.moq.trialStandard}`,
      leadTime: `Muestras en ${fEs.sampleTime} · producción en ${fEs.leadTime} tras confirmar PO y depósito`,
      specRows: [
        { label: 'Escenario de uso', value: 'Travesías de larga distancia, programas de expedición, retail premium' },
        { label: 'Tamaños disponibles', value: "11'6\"–12'6\" × 30\"–32\" × 150 mm" },
        { label: 'Construcción', value: 'Drop-stitch woven + cinta de rail doble reforzada' },
        { label: 'Peso del rider', value: '75–130 kg óptimo' },
        { label: 'Carga máxima', value: '160 kg' },
        { label: 'Presión recomendada / máxima', value: '15,0 / 20,0 PSI' },
        { label: 'Sistema de aletas', value: 'Caja US / opciones deslizantes' },
        { label: 'Paquete estándar', value: 'Bomba, pala, mochila, aleta, leash, kit de reparación' },
      ],
      keyQuestions: [
        'Necesidades de volumen y capacidad de carga',
        'Bungees delantero/trasero y puntos de montaje',
        'Posicionamiento de crucero de larga distancia y largo de tabla objetivo',
      ],
    },
    yoga: {
      bestFor: 'Estudios de fitness acuático, wellness de resort y flotas de SUP yoga',
      sizes: "10'8\"–11'0\" · 34\"–36\" ancho · 150 mm",
      construction: 'Plataforma estable ancha + tracción EVA grabada en toda la cubierta',
      customization: 'Cobertura EVA, arte, anclas y kit de accesorios',
      moq: `Desde ${fEs.moq.standardRun} uds. por proyecto — pedidos de prueba desde ${fEs.moq.trialStandard}`,
      leadTime: `Muestras en ${fEs.sampleTime} · producción en ${fEs.leadTime} tras confirmar PO y depósito`,
      specRows: [
        { label: 'Escenario de uso', value: 'Estudios de fitness acuático, wellness de resort, flotas de SUP yoga' },
        { label: 'Tamaños disponibles', value: "10'8\"–11'0\" × 34\"–36\" × 150 mm" },
        { label: 'Construcción', value: 'Plataforma estable ancha + tracción EVA grabada en toda la cubierta' },
        { label: 'Peso del rider', value: '50–120 kg óptimo' },
        { label: 'Carga máxima', value: '150 kg' },
        { label: 'Presión recomendada / máxima', value: '15,0 / 18,0 PSI' },
        { label: 'Paquete estándar', value: 'Bomba, pala, mochila, aleta, kit de reparación' },
      ],
      keyQuestions: [
        'Cobertura EVA y puntos de anclaje',
        'Cantidad de clases grupales',
        'Frecuencia de uso comercial',
      ],
    },
    whitewater: {
      bestFor: 'Marcas de estilo de vida y diseño, retail boutique',
      sizes: "10'6\"–11'6\" · 32\"–34\" ancho",
      construction: 'Drop-stitch y PVC específicos del proyecto con opciones de gofrado',
      customization: 'Arte de toda la tabla, gofrado, piezas EVA y accesorios coordinados',
      moq: `Desde ${fEs.moq.standardRun} uds. por proyecto — pedidos de prueba desde ${fEs.moq.trialStandard}`,
      leadTime: `Muestras en ${fEs.sampleTime} · producción en ${fEs.leadTime} tras confirmar PO y depósito`,
      specRows: [
        { label: 'Escenario de uso', value: 'Ediciones de diseño, retail de estilo de vida, programas boutique' },
        { label: 'Tamaños disponibles', value: "10'6\"–11'6\" × 32\"–34\" ancho" },
        { label: 'Construcción', value: 'Drop-stitch y PVC específicos del proyecto, opciones de gofrado mecánico' },
        { label: 'Sistema de aletas', value: 'Caja US / opciones deslizantes' },
        { label: 'Paquete estándar', value: 'Bomba, pala, mochila, aleta, kit de reparación' },
      ],
      keyQuestions: [
        'Complejidad del arte y método de impresión',
        'Kit de accesorios coordinados',
        'Estilo de embalaje minorista',
      ],
    },
    fishing: {
      bestFor: 'Marcas de pesca, outfitters y tiendas deportivas',
      sizes: "11'6\"–12'0\" · 34\"–38\" ancho · 150 mm",
      construction: 'Doble capa resistente + múltiples D-rings y montajes de accesorios',
      customization: 'Integración de asiento, nevera y portacañas, distribución de D-rings',
      moq: `Desde ${fEs.moq.standardRun} uds. por proyecto — pedidos de prueba desde ${fEs.moq.trialStandard}`,
      leadTime: `Muestras en ${fEs.sampleTime} · producción en ${fEs.leadTime} tras confirmar PO y depósito`,
      specRows: [
        { label: 'Escenario de uso', value: 'Marcas de equipos de pesca, outfitters, tiendas deportivas' },
        { label: 'Tamaños disponibles', value: "11'6\"–12'0\" × 34\"–38\" × 150 mm" },
        { label: 'Construcción', value: 'Doble capa resistente + múltiples D-rings y montajes de accesorios' },
        { label: 'Peso del rider', value: '80–150 kg óptimo' },
        { label: 'Carga máxima', value: '200 kg' },
        { label: 'Presión recomendada / máxima', value: '15,0 / 18,0 PSI' },
        { label: 'Paquete estándar', value: 'Bomba, pala, mochila, aleta, kit de reparación' },
      ],
      keyQuestions: [
        'Integración de asiento, nevera y portacañas',
        'Distribución de D-rings / rails y necesidades de carga',
        'Objetivo de estabilidad de pie',
      ],
    },
    kids: {
      bestFor: 'Clubes de remo juvenil, escuelas y marcas retail familiares',
      sizes: "8'0\"–9'6\" · 26\"–28\" ancho · 100/120 mm",
      construction: 'Drop-stitch ligero + gráficos de seguridad de alta visibilidad',
      customization: 'Tallas por edad, colorways visibles y longitud de pala',
      moq: `Desde ${fEs.moq.standardRun} uds. por proyecto — pedidos de prueba desde ${fEs.moq.trialStandard}`,
      leadTime: `Muestras en ${fEs.sampleTime} · producción en ${fEs.leadTime} tras confirmar PO y depósito`,
      specRows: [
        { label: 'Escenario de uso', value: 'Clubes de remo juvenil, educación física escolar, retail familiar' },
        { label: 'Tamaños disponibles', value: "8'0\"–9'6\" × 26\"–28\" × 100/120 mm" },
        { label: 'Construcción', value: 'Drop-stitch ligero + gráficos de seguridad de alta visibilidad' },
        { label: 'Peso del rider', value: '30–65 kg óptimo' },
        { label: 'Carga máxima', value: '80 kg' },
        { label: 'Presión recomendada / máxima', value: '12,0 / 15,0 PSI' },
        { label: 'Paquete estándar', value: 'Bomba, pala infantil, mochila, aleta, kit de reparación' },
      ],
      keyQuestions: [
        'Rango de edad y peso de tabla objetivo',
        'Colorway de visibilidad y longitud de pala',
        'Volumen del programa escolar o de club',
      ],
    },
    multi: {
      bestFor: 'Organizadores de team building, parques acuáticos y operadores turísticos',
      sizes: "15'0\"–18'0\" · 50\"–60\" ancho · 200 mm",
      construction: 'Drop-stitch woven multicámara resistente, válvulas dobles',
      customization: 'Numeración de flota, ubicación del logo, asas y distribución de D-rings',
      moq: `Desde ${fEs.moq.standardRun} uds. por proyecto — pedidos de prueba desde ${fEs.moq.trialStandard}`,
      leadTime: `Muestras en ${fEs.sampleTime} · producción en ${fEs.leadTime} tras confirmar PO y depósito`,
      specRows: [
        { label: 'Escenario de uso', value: 'Organizadores de team building, parques acuáticos, operadores turísticos' },
        { label: 'Tamaños disponibles', value: "15'0\"–18'0\" × 50\"–60\" × 200 mm" },
        { label: 'Construcción', value: 'Drop-stitch woven multicámara resistente, válvulas dobles' },
        { label: 'Tripulación', value: '4–8 riders' },
        { label: 'Carga máxima', value: '650 kg' },
        { label: 'Presión recomendada / máxima', value: '15,0 / 18,0 PSI' },
        { label: 'Paquete estándar', value: 'Bomba(s), palas, mochila(s), kit de reparación' },
      ],
      keyQuestions: [
        'Número de riders y carga total',
        'Escenario operativo y condiciones de almacenamiento',
        'Numeración de flota y branding',
      ],
    },
  },
  fr: {
    'all-around': {
      bestFor: 'Retail d’entrée de gamme, resorts et programmes de location',
      sizes: "10'0\"–11'6\" · 31\"–34\" de large · 120/150 mm",
      construction: 'Drop-stitch monocouche fusionnée ou MSL double couche',
      customization: 'Graphismes, EVA, accessoires et emballage retail',
      moq: `À partir de ${fFr.moq.standardRun} pièces par projet — séries d’essai dès ${fFr.moq.trialStandard}`,
      leadTime: `Échantillons en ${fFr.sampleTime} · production en ${fFr.leadTime} après confirmation du bon de commande et du dépôt`,
      specRows: [
        { label: 'Scénario d’utilisation', value: 'Gammes retail d’entrée de gamme, programmes de resort et de location, e-commerce DTC' },
        { label: 'Tailles disponibles', value: "10'0\"–11'6\" × 31\"–34\" × 120/150 mm" },
        { label: 'Construction', value: 'Drop-stitch monocouche fusionnée / MSL double couche' },
        { label: 'Poids du rider', value: '60–110 kg optimal' },
        { label: 'Charge maximale', value: '140 kg' },
        { label: 'Pression recommandée / maximale', value: '15,0 / 18,0 PSI' },
        { label: 'Système d’ailerons', value: 'Boîtier US / options coulissantes' },
        { label: 'Paquet standard', value: 'Pompe, pagaie, sac à dos, aileron, leash, kit de réparation' },
      ],
      keyQuestions: [
        'Niveau de retail visé et profil du rider',
        'Utilisation solo ou familiale/en duo',
        'Kit d’accessoires standard ou complet',
      ],
    },
    race: {
      bestFor: 'Clubs de course, académies d’entraînement et marques de performance',
      sizes: "12'6\"–14'0\" · 24\"–27\" de large · 150 mm",
      construction: 'Drop-stitch tissé linéaire ultra-rigide + longeron carbone',
      customization: 'Layup de course, largeur, système d’ailerons et graphismes de club',
      moq: `À partir de ${fFr.moq.standardRun} pièces par projet — séries d’essai dès ${fFr.moq.trialStandard}`,
      leadTime: `Échantillons en ${fFr.sampleTime} · production en ${fFr.leadTime} après confirmation du bon de commande et du dépôt`,
      specRows: [
        { label: 'Scénario d’utilisation', value: 'Clubs de course, académies d’entraînement sportif, marques de performance' },
        { label: 'Tailles disponibles', value: "12'6\"–14'0\" × 24\"–27\" × 150 mm" },
        { label: 'Construction', value: 'Tissé linéaire ultra-rigide + renfort longeron carbone' },
        { label: 'Poids du rider', value: '65–95 kg optimal' },
        { label: 'Charge maximale', value: '120 kg' },
        { label: 'Pression recommandée / maximale', value: '18,0 / 22,0 PSI' },
        { label: 'Système d’ailerons', value: 'Aileron de course / boîtier US / options click-fin' },
        { label: 'Paquet standard', value: 'Pompe, pagaie de course, sac à dos, aileron, kit de réparation' },
      ],
      keyQuestions: [
        'Plateforme 12′6″ ou 14′',
        'Largeur et poids de board cibles',
        'Système d’ailerons et classe de course',
        'Usage club, compétition ou retail',
      ],
    },
    surf: {
      bestFor: 'Marques de surf, écoles de surf et gammes hybrides',
      sizes: "8'6\"–10'6\" · 30\"–34\" de large",
      construction: 'Shape spécifique vague, rails renforcés et rocker relevé',
      customization: 'Rocker, rails, graphismes de deck et options soft-top',
      moq: `À partir de ${fFr.moq.standardRun} pièces par projet — séries d’essai dès ${fFr.moq.trialStandard}`,
      leadTime: `Échantillons en ${fFr.sampleTime} · production en ${fFr.leadTime} après confirmation du bon de commande et du dépôt`,
      specRows: [
        { label: 'Scénario d’utilisation', value: 'Ride de vagues, écoles de surf, gammes retail hybrides' },
        { label: 'Tailles disponibles', value: "8'6\"–10'6\" × 30\"–34\" de large" },
        { label: 'Construction', value: 'Shape spécifique vague avec rails renforcés' },
        { label: 'Système d’ailerons', value: 'Boîtier US / options aileron fixe' },
        { label: 'Paquet standard', value: 'Pompe, pagaie, sac à dos, aileron, kit de réparation' },
      ],
      keyQuestions: [
        'Poids du rider visé et type de vague',
        'Style soft-top ou layup de performance',
        'Flotte mixte avec d’autres plateformes',
      ],
    },
    touring: {
      bestFor: 'Marques d’expédition, flottes de touring et gammes retail premium',
      sizes: "11'6\"–12'6\" · 30\"–32\" de large · 150 mm",
      construction: 'Drop-stitch tissé + double liseré de rail renforcé',
      customization: 'Sandows de chargement, points de fixation, graphismes et accessoires',
      moq: `À partir de ${fFr.moq.standardRun} pièces par projet — séries d’essai dès ${fFr.moq.trialStandard}`,
      leadTime: `Échantillons en ${fFr.sampleTime} · production en ${fFr.leadTime} après confirmation du bon de commande et du dépôt`,
      specRows: [
        { label: 'Scénario d’utilisation', value: 'Touring longue distance, programmes d’expédition, retail premium' },
        { label: 'Tailles disponibles', value: "11'6\"–12'6\" × 30\"–32\" × 150 mm" },
        { label: 'Construction', value: 'Drop-stitch tissé + double liseré de rail renforcé' },
        { label: 'Poids du rider', value: '75–130 kg optimal' },
        { label: 'Charge maximale', value: '160 kg' },
        { label: 'Pression recommandée / maximale', value: '15,0 / 20,0 PSI' },
        { label: 'Système d’ailerons', value: 'Boîtier US / options coulissantes' },
        { label: 'Paquet standard', value: 'Pompe, pagaie, sac à dos, aileron, leash, kit de réparation' },
      ],
      keyQuestions: [
        'Besoins en volume et capacité de chargement',
        'Sandows avant/arrière et points de fixation',
        'Positionnement croisière longue distance et longueur de board cible',
      ],
    },
    yoga: {
      bestFor: 'Studios de fitness aquatique, bien-être de resort et flottes de SUP yoga',
      sizes: "10'8\"–11'0\" · 34\"–36\" de large · 150 mm",
      construction: 'Plateforme large et stable + adhérence EVA gaufrée sur tout le deck',
      customization: 'Couverture EVA, artwork, ancres et kit d’accessoires',
      moq: `À partir de ${fFr.moq.standardRun} pièces par projet — séries d’essai dès ${fFr.moq.trialStandard}`,
      leadTime: `Échantillons en ${fFr.sampleTime} · production en ${fFr.leadTime} après confirmation du bon de commande et du dépôt`,
      specRows: [
        { label: 'Scénario d’utilisation', value: 'Studios de fitness aquatique, retraites bien-être de resort, flottes de SUP yoga' },
        { label: 'Tailles disponibles', value: "10'8\"–11'0\" × 34\"–36\" × 150 mm" },
        { label: 'Construction', value: 'Plateforme large et stable + adhérence EVA gaufrée sur tout le deck' },
        { label: 'Poids du rider', value: '50–120 kg optimal' },
        { label: 'Charge maximale', value: '150 kg' },
        { label: 'Pression recommandée / maximale', value: '15,0 / 18,0 PSI' },
        { label: 'Paquet standard', value: 'Pompe, pagaie, sac à dos, aileron, kit de réparation' },
      ],
      keyQuestions: [
        'Couverture EVA et points d’ancrage',
        'Quantité de cours collectifs',
        'Fréquence d’utilisation commerciale',
      ],
    },
    whitewater: {
      bestFor: 'Marques lifestyle et de design, retail boutique',
      sizes: "10'6\"–11'6\" · 32\"–34\" de large",
      construction: 'Drop-stitch et PVC spécifiques au projet avec options de gaufrage',
      customization: 'Artwork pleine board, gaufrage, pièces EVA et accessoires coordonnés',
      moq: `À partir de ${fFr.moq.standardRun} pièces par projet — séries d’essai dès ${fFr.moq.trialStandard}`,
      leadTime: `Échantillons en ${fFr.sampleTime} · production en ${fFr.leadTime} après confirmation du bon de commande et du dépôt`,
      specRows: [
        { label: 'Scénario d’utilisation', value: 'Éditions design, retail lifestyle, programmes voyage boutique' },
        { label: 'Tailles disponibles', value: "10'6\"–11'6\" × 32\"–34\" de large" },
        { label: 'Construction', value: 'Drop-stitch et PVC spécifiques au projet, options de gaufrage mécanique' },
        { label: 'Système d’ailerons', value: 'Boîtier US / options coulissantes' },
        { label: 'Paquet standard', value: 'Pompe, pagaie, sac à dos, aileron, kit de réparation' },
      ],
      keyQuestions: [
        'Complexité de l’artwork et méthode d’impression',
        'Kit d’accessoires coordonnés',
        'Style d’emballage retail',
      ],
    },
    fishing: {
      bestFor: 'Marques de pêche sportive, outfitters et magasins de sport',
      sizes: "11'6\"–12'0\" · 34\"–38\" de large · 150 mm",
      construction: 'Double couche renforcée + multiples anneaux en D et fixations d’accessoires',
      customization: 'Intégration siège, glacière et porte-cannes, dispositions d’anneaux en D',
      moq: `À partir de ${fFr.moq.standardRun} pièces par projet — séries d’essai dès ${fFr.moq.trialStandard}`,
      leadTime: `Échantillons en ${fFr.sampleTime} · production en ${fFr.leadTime} après confirmation du bon de commande et du dépôt`,
      specRows: [
        { label: 'Scénario d’utilisation', value: 'Marques d’équipement de pêche, outfitters, magasins de sport extérieur' },
        { label: 'Tailles disponibles', value: "11'6\"–12'0\" × 34\"–38\" × 150 mm" },
        { label: 'Construction', value: 'Double couche renforcée + multiples anneaux en D et fixations d’accessoires' },
        { label: 'Poids du rider', value: '80–150 kg optimal' },
        { label: 'Charge maximale', value: '200 kg' },
        { label: 'Pression recommandée / maximale', value: '15,0 / 18,0 PSI' },
        { label: 'Paquet standard', value: 'Pompe, pagaie, sac à dos, aileron, kit de réparation' },
      ],
      keyQuestions: [
        'Intégration siège, glacière et porte-cannes',
        'Disposition des anneaux en D / rails et besoins de charge',
        'Cible de stabilité debout',
      ],
    },
    kids: {
      bestFor: 'Clubs de rame jeunesse, écoles et marques retail familiales',
      sizes: "8'0\"–9'6\" · 26\"–28\" de large · 100/120 mm",
      construction: 'Drop-stitch léger + graphismes de sécurité haute visibilité',
      customization: 'Tailles par âge, coloris haute visibilité et longueur de pagaie',
      moq: `À partir de ${fFr.moq.standardRun} pièces par projet — séries d’essai dès ${fFr.moq.trialStandard}`,
      leadTime: `Échantillons en ${fFr.sampleTime} · production en ${fFr.leadTime} après confirmation du bon de commande et du dépôt`,
      specRows: [
        { label: 'Scénario d’utilisation', value: 'Clubs de rame jeunesse, éducation physique scolaire, retail familial' },
        { label: 'Tailles disponibles', value: "8'0\"–9'6\" × 26\"–28\" × 100/120 mm" },
        { label: 'Construction', value: 'Drop-stitch léger + graphismes de sécurité haute visibilité' },
        { label: 'Poids du rider', value: '30–65 kg optimal' },
        { label: 'Charge maximale', value: '80 kg' },
        { label: 'Pression recommandée / maximale', value: '12,0 / 15,0 PSI' },
        { label: 'Paquet standard', value: 'Pompe, pagaie enfant, sac à dos, aileron, kit de réparation' },
      ],
      keyQuestions: [
        'Tranche d’âge et poids de board cible',
        'Coloris haute visibilité et longueur de pagaie assortie',
        'Volume programme scolaire ou club',
      ],
    },
    multi: {
      bestFor: 'Organisateurs de team building, parcs aquatiques et opérateurs touristiques',
      sizes: "15'0\"–18'0\" · 50\"–60\" de large · 200 mm",
      construction: 'Drop-stitch tissé multichambre renforcé, double valves',
      customization: 'Numérotation de flotte, placement du logo, poignées et dispositions d’anneaux en D',
      moq: `À partir de ${fFr.moq.standardRun} pièces par projet — séries d’essai dès ${fFr.moq.trialStandard}`,
      leadTime: `Échantillons en ${fFr.sampleTime} · production en ${fFr.leadTime} après confirmation du bon de commande et du dépôt`,
      specRows: [
        { label: 'Scénario d’utilisation', value: 'Organisateurs de team building, parcs aquatiques, opérateurs touristiques' },
        { label: 'Tailles disponibles', value: "15'0\"–18'0\" × 50\"–60\" × 200 mm" },
        { label: 'Construction', value: 'Drop-stitch tissé multichambre renforcé, double valves' },
        { label: 'Équipage', value: '4–8 riders' },
        { label: 'Charge maximale', value: '650 kg' },
        { label: 'Pression recommandée / maximale', value: '15,0 / 18,0 PSI' },
        { label: 'Paquet standard', value: 'Pompe(s), pagaies, sac(s) à dos, kit de réparation' },
      ],
      keyQuestions: [
        'Nombre de riders et charge totale',
        'Scénario opérationnel et conditions de stockage',
        'Numérotation de flotte et branding',
      ],
    },
  },
  de: {
    'all-around': {
      bestFor: 'Einsteiger-Retail, Resorts und Verleihprogramme',
      sizes: "10'0\"–11'6\" · 31\"–34\" breit · 120/150 mm",
      construction: 'Single-Layer-Fusion oder MSL-Doppellagen-Drop-Stitch',
      customization: 'Grafiken, EVA, Zubehör und Retail-Verpackung',
      moq: `Ab ${fDe.moq.standardRun} Stück pro Projekt — Probeproduktionen ab ${fDe.moq.trialStandard}`,
      leadTime: `Muster in ${fDe.sampleTime} · Produktion in ${fDe.leadTime} nach bestätigter Bestellung und Anzahlung`,
      specRows: [
        { label: 'Einsatzszenario', value: 'Einsteiger-Retail, Resort- und Verleihprogramme, DTC-E-Commerce' },
        { label: 'Verfügbare Größen', value: "10'0\"–11'6\" × 31\"–34\" × 120/150 mm" },
        { label: 'Aufbau', value: 'Single-Layer-Fusion / MSL-Doppellagen-Drop-Stitch' },
        { label: 'Gewicht des Riders', value: '60–110 kg optimal' },
        { label: 'Maximale Zuladung', value: '140 kg' },
        { label: 'Empfohlener / maximaler Druck', value: '15.0 / 18.0 PSI' },
        { label: 'Finnen-System', value: 'US-Box / Slide-in-Optionen' },
        { label: 'Standardausstattung', value: 'Pumpe, Paddel, Rucksack, Finne, Leash, Reparaturset' },
      ],
      keyQuestions: [
        'Angestrebte Einzelhandelsstufe und Rider-Profil',
        'Einzelnutzer oder Familien-/Duo-Nutzung',
        'Standard- oder Komplett-Zubehörset',
      ],
    },
    race: {
      bestFor: 'Racing-Clubs, Trainingsakademien und Performance-Marken',
      sizes: "12'6\"–14'0\" · 24\"–27\" breit · 150 mm",
      construction: 'Ultra-steifes Linear-Woven-Drop-Stitch + Carbon-Stringer',
      customization: 'Race-Layup, Breite, Finnen-System und Club-Grafiken',
      moq: `Ab ${fDe.moq.standardRun} Stück pro Projekt — Probeproduktionen ab ${fDe.moq.trialStandard}`,
      leadTime: `Muster in ${fDe.sampleTime} · Produktion in ${fDe.leadTime} nach bestätigter Bestellung und Anzahlung`,
      specRows: [
        { label: 'Einsatzszenario', value: 'Racing-Clubs, Sportakademien, Performance-Marken' },
        { label: 'Verfügbare Größen', value: "12'6\"–14'0\" × 24\"–27\" × 150 mm" },
        { label: 'Aufbau', value: 'Ultra-steifes Linear-Woven + Carbon-Stringer-Verstärkung' },
        { label: 'Gewicht des Riders', value: '65–95 kg optimal' },
        { label: 'Maximale Zuladung', value: '120 kg' },
        { label: 'Empfohlener / maximaler Druck', value: '18.0 / 22.0 PSI' },
        { label: 'Finnen-System', value: 'Race-Finne / US-Box / Click-Fin-Optionen' },
        { label: 'Standardausstattung', value: 'Pumpe, Race-Paddel, Rucksack, Finne, Reparaturset' },
      ],
      keyQuestions: [
        "12'6\"- oder 14'-Plattform",
        'Zielbreite und Boardgewicht',
        'Finnen-System und Racing-Klasse',
        'Club-, Wettkampf- oder Einzelhandelseinsatz',
      ],
    },
    surf: {
      bestFor: 'Surfmarken, Surfschulen und hybride Produktlinien',
      sizes: "8'6\"–10'6\" · 30\"–34\" breit",
      construction: 'Wellenspezifisches Shaping, verstärkte Rails und erhöhter Rocker',
      customization: 'Rocker, Rails, Deck-Grafiken und Soft-Top-Optionen',
      moq: `Ab ${fDe.moq.standardRun} Stück pro Projekt — Probeproduktionen ab ${fDe.moq.trialStandard}`,
      leadTime: `Muster in ${fDe.sampleTime} · Produktion in ${fDe.leadTime} nach bestätigter Bestellung und Anzahlung`,
      specRows: [
        { label: 'Einsatzszenario', value: 'Wellenreiten, Surfschulen, hybride Retail-Linien' },
        { label: 'Verfügbare Größen', value: "8'6\"–10'6\" × 30\"–34\" breit" },
        { label: 'Aufbau', value: 'Wellenspezifisches Shaping mit verstärkten Rails' },
        { label: 'Finnen-System', value: 'US-Box / Festfinne-Optionen' },
        { label: 'Standardausstattung', value: 'Pumpe, Paddel, Rucksack, Finne, Reparaturset' },
      ],
      keyQuestions: [
        'Ziel-Ridergewicht und Wellentyp',
        'Soft-Top-Stil oder Performance-Layup',
        'Gemischte Flotte mit anderen Plattformen',
      ],
    },
    touring: {
      bestFor: 'Expeditionsmarken, Touring-Flotten und Premium-Retail-Linien',
      sizes: "11'6\"–12'6\" · 30\"–32\" breit · 150 mm",
      construction: 'Woven-Drop-Stitch + verstärktes doppeltes Rail-Tape',
      customization: 'Lade-Bungees, Befestigungspunkte, Grafiken und Zubehör',
      moq: `Ab ${fDe.moq.standardRun} Stück pro Projekt — Probeproduktionen ab ${fDe.moq.trialStandard}`,
      leadTime: `Muster in ${fDe.sampleTime} · Produktion in ${fDe.leadTime} nach bestätigter Bestellung und Anzahlung`,
      specRows: [
        { label: 'Einsatzszenario', value: 'Langstrecken-Touren, Expeditionsprogramme, Premium-Retail' },
        { label: 'Verfügbare Größen', value: "11'6\"–12'6\" × 30\"–32\" × 150 mm" },
        { label: 'Aufbau', value: 'Woven-Drop-Stitch + verstärktes doppeltes Rail-Tape' },
        { label: 'Gewicht des Riders', value: '75–130 kg optimal' },
        { label: 'Maximale Zuladung', value: '160 kg' },
        { label: 'Empfohlener / maximaler Druck', value: '15.0 / 20.0 PSI' },
        { label: 'Finnen-System', value: 'US-Box / Slide-in-Optionen' },
        { label: 'Standardausstattung', value: 'Pumpe, Paddel, Rucksack, Finne, Leash, Reparaturset' },
      ],
      keyQuestions: [
        'Anforderungen an Volumen und Ladekapazität',
        'Front-/Heck-Bungees und Befestigungspunkte',
        'Positionierung für Langstreckenfahrten und Ziel-Boardlänge',
      ],
    },
    yoga: {
      bestFor: 'Wasserfitness-Studios, Resort-Wellness und SUP-Yoga-Flotten',
      sizes: "10'8\"–11'0\" · 34\"–36\" breit · 150 mm",
      construction: 'Breite stabile Plattform + vollflächig geprägte EVA-Traktion',
      customization: 'EVA-Abdeckung, Artwork, Anker und Zubehörset',
      moq: `Ab ${fDe.moq.standardRun} Stück pro Projekt — Probeproduktionen ab ${fDe.moq.trialStandard}`,
      leadTime: `Muster in ${fDe.sampleTime} · Produktion in ${fDe.leadTime} nach bestätigter Bestellung und Anzahlung`,
      specRows: [
        { label: 'Einsatzszenario', value: 'Wasserfitness-Studios, Resort-Wellness-Retreats, SUP-Yoga-Flotten' },
        { label: 'Verfügbare Größen', value: "10'8\"–11'0\" × 34\"–36\" × 150 mm" },
        { label: 'Aufbau', value: 'Breite stabile Plattform + vollflächig geprägte EVA-Traktion' },
        { label: 'Gewicht des Riders', value: '50–120 kg optimal' },
        { label: 'Maximale Zuladung', value: '150 kg' },
        { label: 'Empfohlener / maximaler Druck', value: '15.0 / 18.0 PSI' },
        { label: 'Standardausstattung', value: 'Pumpe, Paddel, Rucksack, Finne, Reparaturset' },
      ],
      keyQuestions: [
        'EVA-Abdeckung und Ankerpunkte',
        'Menge für Gruppenkurse',
        'Häufigkeit der kommerziellen Nutzung',
      ],
    },
    whitewater: {
      bestFor: 'Lifestyle- und Designermarken, Boutique-Retail',
      sizes: "10'6\"–11'6\" · 32\"–34\" breit",
      construction: 'Projektspezifisches Drop-Stitch und PVC mit Prägeoptionen',
      customization: 'Vollflächiges Artwork, Prägung, EVA-Konfektionierung und abgestimmtes Zubehör',
      moq: `Ab ${fDe.moq.standardRun} Stück pro Projekt — Probeproduktionen ab ${fDe.moq.trialStandard}`,
      leadTime: `Muster in ${fDe.sampleTime} · Produktion in ${fDe.leadTime} nach bestätigter Bestellung und Anzahlung`,
      specRows: [
        { label: 'Einsatzszenario', value: 'Designer-Editionen, Lifestyle-Retail, Boutique-Reiseprogramme' },
        { label: 'Verfügbare Größen', value: "10'6\"–11'6\" × 32\"–34\" breit" },
        { label: 'Aufbau', value: 'Projektspezifisches Drop-Stitch und PVC, mechanische Prägeoptionen' },
        { label: 'Finnen-System', value: 'US-Box / Slide-in-Optionen' },
        { label: 'Standardausstattung', value: 'Pumpe, Paddel, Rucksack, Finne, Reparaturset' },
      ],
      keyQuestions: [
        'Komplexität des Artworks und Druckverfahren',
        'Abgestimmtes Zubehörset',
        'Retail-Verpackungsstil',
      ],
    },
    fishing: {
      bestFor: 'Anglermarken, Fishing-Outfitter und Sportgeschäfte',
      sizes: "11'6\"–12'0\" · 34\"–38\" breit · 150 mm",
      construction: 'Robuste Doppellage + mehrere D-Ringe und Zubehörhalterungen',
      customization: 'Integration von Sitz, Kühlbox und Rutenhalter, D-Ring-Layouts',
      moq: `Ab ${fDe.moq.standardRun} Stück pro Projekt — Probeproduktionen ab ${fDe.moq.trialStandard}`,
      leadTime: `Muster in ${fDe.sampleTime} · Produktion in ${fDe.leadTime} nach bestätigter Bestellung und Anzahlung`,
      specRows: [
        { label: 'Einsatzszenario', value: 'Anglermarken, Fishing-Outfitter, Outdoor-Sportgeschäfte' },
        { label: 'Verfügbare Größen', value: "11'6\"–12'0\" × 34\"–38\" × 150 mm" },
        { label: 'Aufbau', value: 'Robuste Doppellage + mehrere D-Ringe und Zubehörhalterungen' },
        { label: 'Gewicht des Riders', value: '80–150 kg optimal' },
        { label: 'Maximale Zuladung', value: '200 kg' },
        { label: 'Empfohlener / maximaler Druck', value: '15.0 / 18.0 PSI' },
        { label: 'Standardausstattung', value: 'Pumpe, Paddel, Rucksack, Finne, Reparaturset' },
      ],
      keyQuestions: [
        'Integration von Sitz, Kühlbox und Rutenhalter',
        'D-Ring-/Rail-Layout und Anforderungen an die Zuladung',
        'Ziel für Standstabilität',
      ],
    },
    kids: {
      bestFor: 'Jugend-Paddelclubs, Schulen und Familien-Retail-Marken',
      sizes: "8'0\"–9'6\" · 26\"–28\" breit · 100/120 mm",
      construction: 'Leichtes Drop-Stitch + Sicherheitsgrafiken mit hoher Sichtbarkeit',
      customization: 'Altersgerechte Größen, auffällige Farbvarianten und Paddellänge',
      moq: `Ab ${fDe.moq.standardRun} Stück pro Projekt — Probeproduktionen ab ${fDe.moq.trialStandard}`,
      leadTime: `Muster in ${fDe.sampleTime} · Produktion in ${fDe.leadTime} nach bestätigter Bestellung und Anzahlung`,
      specRows: [
        { label: 'Einsatzszenario', value: 'Jugend-Paddelclubs, Schulsport, Familien-Retail' },
        { label: 'Verfügbare Größen', value: "8'0\"–9'6\" × 26\"–28\" × 100/120 mm" },
        { label: 'Aufbau', value: 'Leichtes Drop-Stitch + Sicherheitsgrafiken mit hoher Sichtbarkeit' },
        { label: 'Gewicht des Riders', value: '30–65 kg optimal' },
        { label: 'Maximale Zuladung', value: '80 kg' },
        { label: 'Empfohlener / maximaler Druck', value: '12.0 / 15.0 PSI' },
        { label: 'Standardausstattung', value: 'Pumpe, Kinderpaddel, Rucksack, Finne, Reparaturset' },
      ],
      keyQuestions: [
        'Altersspanne und Ziel-Boardgewicht',
        'Auffällige Farbvariante und passende Paddellänge',
        'Programmvolumen für Schule oder Club',
      ],
    },
    multi: {
      bestFor: 'Teambuilding-Organisatoren, Wasserparks und kommerzielle Touranbieter',
      sizes: "15'0\"–18'0\" · 50\"–60\" breit · 200 mm",
      construction: 'Robustes mehrkammeriges Woven-Drop-Stitch, Doppelventile',
      customization: 'Flottennummerierung, Logo-Positionierung, Griffe und D-Ring-Layouts',
      moq: `Ab ${fDe.moq.standardRun} Stück pro Projekt — Probeproduktionen ab ${fDe.moq.trialStandard}`,
      leadTime: `Muster in ${fDe.sampleTime} · Produktion in ${fDe.leadTime} nach bestätigter Bestellung und Anzahlung`,
      specRows: [
        { label: 'Einsatzszenario', value: 'Teambuilding-Organisatoren, Wasserparks, kommerzielle Touranbieter' },
        { label: 'Verfügbare Größen', value: "15'0\"–18'0\" × 50\"–60\" × 200 mm" },
        { label: 'Aufbau', value: 'Robustes mehrkammeriges Woven-Drop-Stitch, Doppelventile' },
        { label: 'Crew-Größe', value: '4–8 Rider' },
        { label: 'Maximale Zuladung', value: '650 kg' },
        { label: 'Empfohlener / maximaler Druck', value: '15.0 / 18.0 PSI' },
        { label: 'Standardausstattung', value: 'Pumpe(n), Paddel, Rucksack/Rucksäcke, Reparaturset' },
      ],
      keyQuestions: [
        'Anzahl der Rider und Gesamtzuladung',
        'Einsatzszenario und Lagerbedingungen',
        'Flottennummerierung und Branding',
      ],
    },
  },
  it: {
    'all-around': {
      bestFor: 'Retail di ingresso, resort e programmi di noleggio',
      sizes: "10'0\"–11'6\" · 31\"–34\" larghezza · 120/150 mm",
      construction: 'Drop-stitch a fusione a strato singolo o MSL a doppio strato',
      customization: 'Grafiche, EVA, accessori e imballaggio retail',
      moq: `Da ${fIt.moq.standardRun} pz per progetto — ordini di prova da ${fIt.moq.trialStandard}`,
      leadTime: `Campioni in ${fIt.sampleTime} · produzione in ${fIt.leadTime} dopo PO confermato e acconto`,
      specRows: [
        { label: 'Uso previsto', value: 'Linee retail di ingresso, programmi per resort e noleggio, e-commerce DTC' },
        { label: 'Misure disponibili', value: "10'0\"–11'6\" × 31\"–34\" × 120/150 mm" },
        { label: 'Costruzione', value: 'Drop-stitch a fusione a strato singolo / MSL a doppio strato' },
        { label: 'Peso del rider', value: '60–110 kg ottimale' },
        { label: 'Carico massimo', value: '140 kg' },
        { label: 'Pressione consigliata / massima', value: '15.0 / 18.0 PSI' },
        { label: 'Sistema di alette', value: 'US box / opzioni slide-in' },
        { label: 'Pacchetto standard', value: 'Pompa, pagaia, zaino, aletta, leash, kit di riparazione' },
      ],
      keyQuestions: [
        'Livello retail target e profilo del rider',
        'Uso singolo o familiare/a due',
        'Kit accessori standard o completo',
      ],
    },
    race: {
      bestFor: 'Club di gara, accademie di allenamento e marchi performance',
      sizes: "12'6\"–14'0\" · 24\"–27\" larghezza · 150 mm",
      construction: 'Drop-stitch woven lineare ultra-rigido + stringer in carbonio',
      customization: 'Layup da gara, larghezza, sistema alette e grafiche del club',
      moq: `Da ${fIt.moq.standardRun} pz per progetto — ordini di prova da ${fIt.moq.trialStandard}`,
      leadTime: `Campioni in ${fIt.sampleTime} · produzione in ${fIt.leadTime} dopo PO confermato e acconto`,
      specRows: [
        { label: 'Uso previsto', value: 'Club di gara, accademie sportive, marchi performance' },
        { label: 'Misure disponibili', value: "12'6\"–14'0\" × 24\"–27\" × 150 mm" },
        { label: 'Costruzione', value: 'Woven lineare ultra-rigido + rinforzo stringer in carbonio' },
        { label: 'Peso del rider', value: '65–95 kg ottimale' },
        { label: 'Carico massimo', value: '120 kg' },
        { label: 'Pressione consigliata / massima', value: '18.0 / 22.0 PSI' },
        { label: 'Sistema di alette', value: 'Aletta da gara / US box / opzioni click-fin' },
        { label: 'Pacchetto standard', value: 'Pompa, pagaia da gara, zaino, aletta, kit di riparazione' },
      ],
      keyQuestions: [
        'Piattaforma 12′6″ o 14′',
        'Larghezza e peso della tavola target',
        'Sistema di alette e classe di gara',
        'Uso club, gara o retail',
      ],
    },
    surf: {
      bestFor: 'Marchi di surf, scuole di surf e linee ibride',
      sizes: "8'6\"–10'6\" · 30\"–34\" larghezza",
      construction: 'Sagomatura specifica per onda, rails rinforzati e rocker rialzato',
      customization: 'Rocker, rails, grafiche del deck e opzioni soft-top',
      moq: `Da ${fIt.moq.standardRun} pz per progetto — ordini di prova da ${fIt.moq.trialStandard}`,
      leadTime: `Campioni in ${fIt.sampleTime} · produzione in ${fIt.leadTime} dopo PO confermato e acconto`,
      specRows: [
        { label: 'Uso previsto', value: 'Surf sulle onde, scuole di surf, linee retail ibride' },
        { label: 'Misure disponibili', value: "8'6\"–10'6\" × 30\"–34\" larghezza" },
        { label: 'Costruzione', value: 'Sagomatura specifica per onda con rails rinforzati' },
        { label: 'Sistema di alette', value: 'US box / opzioni aletta fissa' },
        { label: 'Pacchetto standard', value: 'Pompa, pagaia, zaino, aletta, kit di riparazione' },
      ],
      keyQuestions: [
        'Peso del rider target e tipo di onda',
        'Stile soft-top o layup performance',
        'Flotta mista con altre piattaforme',
      ],
    },
    touring: {
      bestFor: 'Marchi di spedizioni, flotte touring e linee retail premium',
      sizes: "11'6\"–12'6\" · 30\"–32\" larghezza · 150 mm",
      construction: 'Drop-stitch woven + doppio nastro rail rinforzato',
      customization: 'Bungee di carico, punti di fissaggio, grafiche e accessori',
      moq: `Da ${fIt.moq.standardRun} pz per progetto — ordini di prova da ${fIt.moq.trialStandard}`,
      leadTime: `Campioni in ${fIt.sampleTime} · produzione in ${fIt.leadTime} dopo PO confermato e acconto`,
      specRows: [
        { label: 'Uso previsto', value: 'Tour di lunga distanza, programmi di spedizione, retail premium' },
        { label: 'Misure disponibili', value: "11'6\"–12'6\" × 30\"–32\" × 150 mm" },
        { label: 'Costruzione', value: 'Drop-stitch woven + doppio nastro rail rinforzato' },
        { label: 'Peso del rider', value: '75–130 kg ottimale' },
        { label: 'Carico massimo', value: '160 kg' },
        { label: 'Pressione consigliata / massima', value: '15.0 / 20.0 PSI' },
        { label: 'Sistema di alette', value: 'US box / opzioni slide-in' },
        { label: 'Pacchetto standard', value: 'Pompa, pagaia, zaino, aletta, leash, kit di riparazione' },
      ],
      keyQuestions: [
        'Esigenze di volume e capacità di carico',
        'Bungee anteriori/posteriori e punti di fissaggio',
        'Posizionamento per lunghe crociere e lunghezza della tavola target',
      ],
    },
    yoga: {
      bestFor: 'Studi di fitness acquatico, wellness di resort e flotte SUP yoga',
      sizes: "10'8\"–11'0\" · 34\"–36\" larghezza · 150 mm",
      construction: 'Piattaforma larga e stabile + trazione EVA a rilievo su tutto il deck',
      customization: 'Copertura EVA, grafiche, ancoraggi e kit accessori',
      moq: `Da ${fIt.moq.standardRun} pz per progetto — ordini di prova da ${fIt.moq.trialStandard}`,
      leadTime: `Campioni in ${fIt.sampleTime} · produzione in ${fIt.leadTime} dopo PO confermato e acconto`,
      specRows: [
        { label: 'Uso previsto', value: 'Studi di fitness acquatico, ritiri wellness di resort, flotte SUP yoga' },
        { label: 'Misure disponibili', value: "10'8\"–11'0\" × 34\"–36\" × 150 mm" },
        { label: 'Costruzione', value: 'Piattaforma larga e stabile + trazione EVA a rilievo su tutto il deck' },
        { label: 'Peso del rider', value: '50–120 kg ottimale' },
        { label: 'Carico massimo', value: '150 kg' },
        { label: 'Pressione consigliata / massima', value: '15.0 / 18.0 PSI' },
        { label: 'Pacchetto standard', value: 'Pompa, pagaia, zaino, aletta, kit di riparazione' },
      ],
      keyQuestions: [
        'Copertura EVA e punti di ancoraggio',
        'Quantità per lezioni di gruppo',
        'Frequenza d’uso commerciale',
      ],
    },
    whitewater: {
      bestFor: 'Marchi lifestyle e di design, retail boutique',
      sizes: "10'6\"–11'6\" · 32\"–34\" larghezza",
      construction: 'Drop-stitch e PVC specifici del progetto con opzioni a rilievo',
      customization: 'Grafiche su tutta la tavola, rilievo, lavorazioni EVA e accessori coordinati',
      moq: `Da ${fIt.moq.standardRun} pz per progetto — ordini di prova da ${fIt.moq.trialStandard}`,
      leadTime: `Campioni in ${fIt.sampleTime} · produzione in ${fIt.leadTime} dopo PO confermato e acconto`,
      specRows: [
        { label: 'Uso previsto', value: 'Edizioni firmate, retail lifestyle, programmi travel boutique' },
        { label: 'Misure disponibili', value: "10'6\"–11'6\" × 32\"–34\" larghezza" },
        { label: 'Costruzione', value: 'Drop-stitch e PVC specifici del progetto, opzioni di rilievo meccanico' },
        { label: 'Sistema di alette', value: 'US box / opzioni slide-in' },
        { label: 'Pacchetto standard', value: 'Pompa, pagaia, zaino, aletta, kit di riparazione' },
      ],
      keyQuestions: [
        'Complessità delle grafiche e metodo di stampa',
        'Kit accessori coordinati',
        'Stile di imballaggio retail',
      ],
    },
    fishing: {
      bestFor: 'Marchi di pesca, outfitter e negozi sportivi',
      sizes: "11'6\"–12'0\" · 34\"–38\" larghezza · 150 mm",
      construction: 'Doppio strato robusto + più anelli a D e supporti accessori',
      customization: 'Integrazione di sedile, borsa frigo e portacanne, layout degli anelli a D',
      moq: `Da ${fIt.moq.standardRun} pz per progetto — ordini di prova da ${fIt.moq.trialStandard}`,
      leadTime: `Campioni in ${fIt.sampleTime} · produzione in ${fIt.leadTime} dopo PO confermato e acconto`,
      specRows: [
        { label: 'Uso previsto', value: 'Marchi di attrezzatura da pesca, outfitter, negozi sportivi outdoor' },
        { label: 'Misure disponibili', value: "11'6\"–12'0\" × 34\"–38\" × 150 mm" },
        { label: 'Costruzione', value: 'Doppio strato robusto + più anelli a D e supporti accessori' },
        { label: 'Peso del rider', value: '80–150 kg ottimale' },
        { label: 'Carico massimo', value: '200 kg' },
        { label: 'Pressione consigliata / massima', value: '15.0 / 18.0 PSI' },
        { label: 'Pacchetto standard', value: 'Pompa, pagaia, zaino, aletta, kit di riparazione' },
      ],
      keyQuestions: [
        'Integrazione di sedile, borsa frigo e portacanne',
        'Layout anelli a D / rails ed esigenze di carico',
        'Obiettivo di stabilità in piedi',
      ],
    },
    kids: {
      bestFor: 'Club di canottaggio giovanile, scuole e marchi retail familiari',
      sizes: "8'0\"–9'6\" · 26\"–28\" larghezza · 100/120 mm",
      construction: 'Drop-stitch leggero + grafiche di sicurezza ad alta visibilità',
      customization: 'Misure per età, colori ad alta visibilità e lunghezza della pagaia',
      moq: `Da ${fIt.moq.standardRun} pz per progetto — ordini di prova da ${fIt.moq.trialStandard}`,
      leadTime: `Campioni in ${fIt.sampleTime} · produzione in ${fIt.leadTime} dopo PO confermato e acconto`,
      specRows: [
        { label: 'Uso previsto', value: 'Club di canottaggio giovanile, educazione fisica scolastica, retail familiare' },
        { label: 'Misure disponibili', value: "8'0\"–9'6\" × 26\"–28\" × 100/120 mm" },
        { label: 'Costruzione', value: 'Drop-stitch leggero + grafiche di sicurezza ad alta visibilità' },
        { label: 'Peso del rider', value: '30–65 kg ottimale' },
        { label: 'Carico massimo', value: '80 kg' },
        { label: 'Pressione consigliata / massima', value: '12.0 / 15.0 PSI' },
        { label: 'Pacchetto standard', value: 'Pompa, pagaia per bambini, zaino, aletta, kit di riparazione' },
      ],
      keyQuestions: [
        'Fascia d’età e peso della tavola target',
        'Colori ad alta visibilità e lunghezza della pagaia',
        'Volume del programma scolastico o del club',
      ],
    },
    multi: {
      bestFor: 'Organizzatori di team building, parchi acquatici e operatori turistici commerciali',
      sizes: "15'0\"–18'0\" · 50\"–60\" larghezza · 200 mm",
      construction: 'Drop-stitch woven multicamera robusto, doppie valvole',
      customization: 'Numerazione flotta, posizionamento logo, maniglie e layout degli anelli a D',
      moq: `Da ${fIt.moq.standardRun} pz per progetto — ordini di prova da ${fIt.moq.trialStandard}`,
      leadTime: `Campioni in ${fIt.sampleTime} · produzione in ${fIt.leadTime} dopo PO confermato e acconto`,
      specRows: [
        { label: 'Uso previsto', value: 'Organizzatori di team building, parchi acquatici, operatori turistici commerciali' },
        { label: 'Misure disponibili', value: "15'0\"–18'0\" × 50\"–60\" × 200 mm" },
        { label: 'Costruzione', value: 'Drop-stitch woven multicamera robusto, doppie valvole' },
        { label: 'Numero di equipaggio', value: '4–8 rider' },
        { label: 'Carico massimo', value: '650 kg' },
        { label: 'Pressione consigliata / massima', value: '15.0 / 18.0 PSI' },
        { label: 'Pacchetto standard', value: 'Pompa(e), pagaie, zaino/i, kit di riparazione' },
      ],
      keyQuestions: [
        'Numero di rider e carico totale',
        'Scenario operativo e condizioni di stoccaggio',
        'Numerazione flotta e branding',
      ],
    },
  },
}

/** Common commercial rows (MOQ / samples / pricing) for every category page. */
export const commercialRows: Localized<ProcurementRow[]> = {
  en: [
    { label: 'Sample path', value: 'Sample development available for qualified OEM/ODM projects.' },
    { label: 'Sample MOQ', value: 'Confirmed by board platform, artwork complexity and accessory set.' },
    { label: 'Volume MOQ', value: 'MOQ is confirmed per model, colorway, packaging configuration and order mix.' },
    { label: 'Pricing logic', value: 'Quotation is based on construction, size, accessory set, artwork, packaging, order quantity and delivery terms.' },
    { label: 'Sample timing', value: `Samples in ${fEn.sampleTime} after specification, artwork and payment requirements are confirmed.` },
    { label: 'Production timing', value: `Production in ${fEn.leadTime} after sample approval, final artwork, deposit and production scheduling are confirmed.` },
    { label: 'Packaging MOQ', value: 'Custom retail packaging may carry separate MOQ requirements.' },
    { label: 'Mixed orders', value: 'Mixed models or colorways are reviewed according to material, printing and packaging requirements.' },
    { label: 'Inspection', value: 'Third-party inspection and buyer-appointed inspection can be discussed before production release.' },
    { label: 'Commercial terms', value: 'Available terms are discussed during quotation based on project scope and order history.' },
  ],
  es: [
    { label: 'Ruta de muestras', value: 'Desarrollo de muestras disponible para proyectos OEM/ODM calificados.' },
    { label: 'MOQ de muestras', value: 'Confirmado según plataforma de tabla, complejidad del arte y conjunto de accesorios.' },
    { label: 'MOQ de volumen', value: 'El MOQ se confirma por modelo, colorway, configuración de embalaje y mezcla de pedidos.' },
    { label: 'Lógica de precios', value: 'El presupuesto se basa en construcción, tamaño, conjunto de accesorios, arte, embalaje, cantidad de pedido y condiciones comerciales.' },
    { label: 'Tiempo de muestras', value: `Muestras en ${fEs.sampleTime} tras confirmar especificación, arte y requisitos de pago.` },
    { label: 'Tiempo de producción', value: `Producción en ${fEs.leadTime} tras aprobación de muestra, arte final, depósito y programación de producción.` },
    { label: 'MOQ de embalaje', value: 'El embalaje minorista personalizado puede tener requisitos de MOQ independientes.' },
    { label: 'Pedidos mixtos', value: 'Modelos o colorways mixtos se revisan según requisitos de material, impresión y embalaje.' },
    { label: 'Inspección', value: 'La inspección de terceros y la inspección designada por el comprador pueden acordarse antes de la liberación de producción.' },
    { label: 'Condiciones comerciales', value: 'Las condiciones disponibles se analizan durante el presupuesto según el alcance del proyecto y el historial de pedidos.' },
  ],
  fr: [
    { label: 'Parcours d’échantillons', value: 'Développement d’échantillons disponible pour les projets OEM/ODM qualifiés.' },
    { label: 'MOQ d’échantillons', value: 'Confirmé selon la plateforme de board, la complexité de l’artwork et l’ensemble d’accessoires.' },
    { label: 'MOQ de volume', value: 'Le MOQ est confirmé par modèle, coloris, configuration d’emballage et mix de commandes.' },
    { label: 'Logique de prix', value: 'Le devis repose sur la construction, la taille, l’ensemble d’accessoires, l’artwork, l’emballage, la quantité commandée et les conditions de livraison.' },
    { label: 'Délai d’échantillons', value: `Échantillons en ${fFr.sampleTime} après confirmation de la spécification, de l’artwork et des conditions de paiement.` },
    { label: 'Délai de production', value: `Production en ${fFr.leadTime} après approbation de l’échantillon, artwork final, dépôt et planification de la production.` },
    { label: 'MOQ d’emballage', value: 'Un emballage retail personnalisé peut impliquer des exigences de MOQ distinctes.' },
    { label: 'Commandes mixtes', value: 'Les modèles ou coloris mixtes sont étudiés selon les exigences de matériaux, d’impression et d’emballage.' },
    { label: 'Inspection', value: 'Une inspection par tiers et une inspection désignée par l’acheteur peuvent être convenues avant le lancement de la production.' },
    { label: 'Conditions commerciales', value: 'Les conditions disponibles sont discutées lors du devis selon le périmètre du projet et l’historique de commandes.' },
  ],
  de: [
    { label: 'Musterweg', value: 'Musterentwicklung für qualifizierte OEM/ODM-Projekte verfügbar.' },
    { label: 'Muster-MOQ', value: 'Wird anhand der Board-Plattform, der Komplexität des Artworks und des Zubehörumfangs festgelegt.' },
    { label: 'Mengen-MOQ', value: 'Das MOQ wird pro Modell, Farbvariante, Verpackungskonfiguration und Auftragsmix festgelegt.' },
    { label: 'Preislogik', value: 'Das Angebot basiert auf Konstruktion, Größe, Zubehörumfang, Artwork, Verpackung, Bestellmenge und Lieferbedingungen.' },
    { label: 'Musterlaufzeit', value: `Muster in ${fDe.sampleTime} nach Bestätigung von Spezifikation, Artwork und Zahlungsanforderungen.` },
    { label: 'Produktionslaufzeit', value: `Produktion in ${fDe.leadTime} nach Musterfreigabe, finalem Artwork, Anzahlung und Bestätigung des Produktionsplans.` },
    { label: 'Verpackungs-MOQ', value: 'Individuelle Retail-Verpackungen können gesonderte MOQ-Anforderungen haben.' },
    { label: 'Gemischte Aufträge', value: 'Gemischte Modelle oder Farbvarianten werden anhand der Material-, Druck- und Verpackungsanforderungen geprüft.' },
    { label: 'Prüfung', value: 'Prüfungen durch Dritte und vom Käufer beauftragte Prüfungen können vor der Produktionsfreigabe vereinbart werden.' },
    { label: 'Handelsbedingungen', value: 'Verfügbare Bedingungen werden bei der Angebotskalkulation je nach Projektumfang und Auftragshistorie besprochen.' },
  ],
  it: [
    { label: 'Percorso campione', value: 'Sviluppo campioni disponibile per progetti OEM/ODM qualificati.' },
    { label: 'MOQ campione', value: 'Confermato in base a piattaforma della tavola, complessità delle grafiche e set di accessori.' },
    { label: 'MOQ volume', value: 'Il MOQ è confermato per modello, colore, configurazione di imballaggio e mix d’ordine.' },
    { label: 'Logica di prezzo', value: 'Il preventivo si basa su costruzione, misura, set di accessori, grafiche, imballaggio, quantità d’ordine e condizioni di consegna.' },
    { label: 'Tempi campione', value: `Campioni in ${fIt.sampleTime} dopo la conferma di specifica, grafiche e requisiti di pagamento.` },
    { label: 'Tempi di produzione', value: `Produzione in ${fIt.leadTime} dopo l’approvazione del campione, la grafica finale, l’acconto e la pianificazione della produzione.` },
    { label: 'MOQ imballaggio', value: 'L’imballaggio retail su misura può comportare requisiti MOQ separati.' },
    { label: 'Ordini misti', value: 'Modelli o colori misti sono esaminati in base ai requisiti di materiali, stampa e imballaggio.' },
    { label: 'Ispezione', value: 'Ispezione di terze parti e ispezione nominata dall’acquirente possono essere concordate prima del rilascio della produzione.' },
    { label: 'Condizioni commerciali', value: 'Le condizioni disponibili sono discusse durante il preventivo in base all’ambito del progetto e allo storico ordini.' },
  ],
}
